name: CI for ESPHome

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install ESPHome
        run: pip install esphome

      - name: Compile ESPHome configuration
        run: esphome compile halo-v1-template.yaml

      - name: Upload to device
        run: esphome upload halo-v1-template.yaml
        env:
          ESPHOME_DEVICE: ${{ secrets.ESPHOME_DEVICE }}
          ESPHOME_PASSWORD: ${{ secrets.ESPHOME_PASSWORD }}