# Common Templates for Halo V1 Project

# This file contains common templates that can be reused across different configurations.

# Example template for a basic sensor configuration
sensor_template: |
  sensor:
    - platform: dht
      pin: GPIO4
      temperature: temperature_sensor
      humidity: humidity_sensor
      update_interval: 60s

# Example template for a basic display configuration
display_template: |
  display:
    - platform: lvgl
      id: my_display
      width: 240
      height: 320
      rotation: 0

# Example template for a basic LED configuration
led_template: |
  light:
    - platform: rgb
      id: my_led
      red: GPIO12
      green: GPIO13
      blue: GPIO14
      name: "My RGB LED"