# on_load.yaml

on_load:
  - script: 
      id: initialize_device
      then:
        - logger.log: "Device initialization started."
        - delay: 1000ms
        - logger.log: "Device initialization completed."
  - script: 
      id: check_memory
      then:
        - if:
            condition: "memory.available < 10000"
            then:
              - logger.log: "Warning: Low memory available!"
              - logger.log: "Consider reducing active packages."
  - script: 
      id: setup_ble
      then:
        - logger.log: "Setting up BLE configurations."
        - ble.start: 
            name: "HaloDevice"
            advertising_interval: 100ms
  - script: 
      id: load_default_pages
      then:
        - logger.log: "Loading default LVGL pages."
        - lvgl.load_pages: 
            pages: 
              - main_page
              - settings_page
              - info_page