# ============================================================================
# Halo Device Configuration - AirQ + Weather
# ============================================================================
# This is an example configuration for a device with:
#   - Vertical Clock display
#   - Air Quality monitoring (AirQ)
#   - Weather forecasts
#   - WiFi monitoring DISABLED
#   - BLE DISABLED
#
# To use this configuration:
#   1. Copy this file to a new name (e.g., halo-v1-living-room.yaml)
#   2. Update the device name and friendly_name below
#   3. Adjust any other settings as needed
#   4. Commit and push to GitHub
#   5. Build in Home Assistant ESPHome
# ============================================================================

esphome:
  name: halo-v1-airq-weather  # Change this to your device name
  friendly_name: Halo AirQ + Weather  # Change this to your preferred display name
  name_add_mac_suffix: false
  platformio_options:
    upload_speed: 921600
    board_build.flash_mode: qio
    board_build.psram_type: opi
    board_build.f_flash: 80000000L
    board_build.f_cpu: 240000000L

  min_version: 2025.6.2

  project:
    name: "yashmulgaonkar.Halo-v1"
    version: "${version}"

dashboard_import:
  package_import_url: github://truffshuff/halo/TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/Halo-v1.yaml@main
  import_full_config: true

ota:
  - platform: esphome
    id: ota_default

wifi:
  on_connect:
    - delay: 5s # Gives time for improv results to be transmitted

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Halo Hotspot"
    ap_timeout: 0s  # Start AP immediately if no WiFi configured

# Override logger settings to reduce traffic and prevent crashes
logger:
  logs:
    weather_color: WARN
    time_update: WARN
    scd4x: WARN
    text: WARN
    sensor: WARN
    homeassistant.sensor: WARN
    page_rotation: WARN
    text_sensor: WARN
    homeassistant.text_sensor: WARN
    light: WARN
    binary_sensor: WARN
    number: WARN

packages:
  # ========================================
  # UTILITY PACKAGES
  # ========================================

  # Memory Statistics - recommended for debugging
  memory_stats:
    url: https://github.com/truffshuff/halo/
    ref: main
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/memory-stats.yaml]
    refresh: always

  # WiFi Display - shows connection info
  wifi_display:
    url: https://github.com/truffshuff/halo/
    ref: main
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/wifi-display.yaml]
    refresh: always

  # WireGuard VPN - DISABLED for this example
  # Uncomment these 3 packages if you need WireGuard:
  # wireguard:
  #   url: https://github.com/truffshuff/halo/
  #   ref: main
  #   files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/wireguard.yaml]
  #   refresh: always
  # wireguard_display:
  #   url: https://github.com/truffshuff/halo/
  #   ref: main
  #   files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/wireguard-display.yaml]
  #   refresh: always
  # time_update_wireguard:
  #   url: https://github.com/truffshuff/halo/
  #   ref: main
  #   files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/time-update-wireguard.yaml]
  #   refresh: always

  # ========================================
  # ENABLED FEATURES
  # ========================================

  # AirQ monitoring - ENABLED
  airq_core:
    url: https://github.com/truffshuff/halo/
    ref: main
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/airq-core.yaml]
    refresh: always
  airq_display:
    url: https://github.com/truffshuff/halo/
    ref: main
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/airq-display.yaml]
    refresh: always

  # Weather monitoring - ENABLED
  weather_core:
    url: https://github.com/truffshuff/halo/
    ref: main
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/weather-core.yaml]
    refresh: always
  weather_sensors:
    url: https://github.com/truffshuff/halo/
    ref: main
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/weather-sensors.yaml]
    refresh: always
  weather_fonts_text:
    url: https://github.com/truffshuff/halo/
    ref: main
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/weather-fonts-text.yaml]
    refresh: always

  # ========================================
  # DISABLED FEATURES (using stubs)
  # ========================================

  # WiFi monitoring - DISABLED
  wifi_stubs:
    url: https://github.com/truffshuff/halo/
    ref: main
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/wifi-stubs.yaml]
    refresh: always

  # BLE - DISABLED
  ble_stubs:
    url: https://github.com/truffshuff/halo/
    ref: main
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/ble-stubs.yaml]
    refresh: always

  # ========================================
  # CORE CONFIGURATION
  # ========================================

  # Import the rest from core
  remote_package:
    url: https://github.com/truffshuff/halo/
    ref: main
    files:
      - TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/Halo-v1-Core.yaml
    refresh: always

  # ========================================
  # LVGL PAGES - AirQ + Weather
  # ========================================

  # LVGL Pages Configuration - AirQ + Weather (Clock + AirQ + Weather pages)
  # Choose ONE of the following:
  #   - lvgl-pages-full.yaml (all features: clock, AirQ, WiFi, weather)
  #   - lvgl-pages-airq-weather.yaml (clock + AirQ + weather) ← SELECTED
  #   - lvgl-pages-airq-only.yaml (clock + AirQ only)
  #   - lvgl-pages-weather.yaml (clock + weather only)
  #   - lvgl-pages-clock-only.yaml (minimal clock display)
  lvgl_pages:
    url: https://github.com/truffshuff/halo/
    ref: main
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/lvgl-pages-airq-weather.yaml]
    refresh: always

# ============================================================================
# DEVICE-SPECIFIC OVERRIDES
# ============================================================================

# Override Default Page select to only show available pages
select:
  - platform: template
    name: Default Page
    id: default_page_select_boot
    entity_category: "config"
    options:
      - "Vertical Clock"
      - "AirQ"
      - "Weather"
      - "Daily Forecast"
      - "Hourly Forecast"
    initial_option: "Vertical Clock"
    restore_value: true
    optimistic: true
    on_value:
      - lambda: |-
          int idx = 0;
          const std::string &choice = id(default_page_select_boot).state;
          if (choice == "Vertical Clock") idx = 0;
          else if (choice == "AirQ") idx = 1;
          // WiFi page (idx = 2) is disabled
          else if (choice == "Weather") idx = 3;
          else if (choice == "Daily Forecast") idx = 4;
          else if (choice == "Hourly Forecast") idx = 5;
          id(default_page_index) = idx;

# Optimize LVGL buffer for this configuration
# Lower than full-featured since WiFi page is disabled
lvgl:
  buffer_size: 27%  # Good balance for AirQ + Weather
