# ============================================================================
# Halo V1 - GitHub URLs Version for HA Dashboard
# ============================================================================
# This version loads ALL packages from GitHub URLs.
# No local file copying required!
#
# LIMITATIONS:
# - No Jinja2 dynamic configuration (must manually change package URLs)
# - All packages loaded explicitly (no core file wrapper)
# - More verbose than local !include version
#
# ✅ BLE + WEATHER NOW POSSIBLE!
#   Old: BLE (60KB) + Weather sensors (75KB) = Too tight!
#   New: BLE (60KB) + HA Actions (3KB) = Plenty of room!
# ============================================================================

substitutions:
  # Device Identity
  name: "halo-v1-79e384"
  friendly_name: "Halo Air Quality Monitor Dev"

  # Core substitutions
  version: "25.10.30.1828"
  device_description: ${name} - v${version}.

  # Weather configuration (if enabled below)
  weather_entity_id: "weather.hhut"
  weather_refresh_interval: "900"

  # Network Configuration
  wifi_ssid: !secret wifihome_ssid
  wifi_password: !secret wifihome_password

  # Security
  api_encryption_key: "mLKXHYyBZgGLfMiXyWoo3Fzc/TpqbKpk0g+uYAwErMs="
  ota_password: "halo79e384"

# ============================================================================
# PACKAGE IMPORTS - ALL FROM GITHUB
# ============================================================================
# All packages loaded directly from GitHub repository.
# Change URLs to enable/disable features.
# ============================================================================

packages:
  # === ESSENTIAL CORE PACKAGES (from Halo-v1-Core.yaml) ===

  pkg_page_registry:
    url: https://github.com/truffshuff/halo.git
    ref: main
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/page-registry.yaml]
    refresh: always

  pkg_vertical_clock:
    url: https://github.com/truffshuff/halo.git
    ref: main
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/vertical-clock-core.yaml]
    refresh: always

  pkg_time_update:
    url: https://github.com/truffshuff/halo.git
    ref: main
    # CHANGE THIS LINE based on AirQ enabled/disabled:
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/time-update-clock-only.yaml]  # AirQ disabled
    # files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/time-update-basic.yaml]      # AirQ enabled
    refresh: always

  pkg_psram_helpers:
    url: https://github.com/truffshuff/halo.git
    ref: main
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/psram-helpers.yaml]
    refresh: always

  # === FEATURE PACKAGES (Change URLs to enable/disable) ===

  pkg_airq:
    url: https://github.com/truffshuff/halo.git
    ref: main
    # CHANGE THIS LINE to enable/disable AirQ:
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/airq-stubs.yaml]     # ← DISABLED
    # files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/airq-display.yaml]  # ← Enable this for AirQ
    refresh: always

  pkg_ble:
    url: https://github.com/truffshuff/halo.git
    ref: main
    # CHANGE THIS LINE to enable/disable BLE:
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/ble-stubs.yaml]              # ← DISABLED
    # files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/ble-core-simplified.yaml]  # ← Enable this for BLE
    refresh: always

  pkg_wifi:
    url: https://github.com/truffshuff/halo.git
    ref: main
    # CHANGE THIS LINE to enable/disable WiFi page:
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/wifi-stubs.yaml]      # ← DISABLED
    # files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/wifi-display.yaml]  # ← Enable this for WiFi page
    refresh: always

  pkg_weather:
    url: https://github.com/truffshuff/halo.git
    ref: main
    # CHANGE THIS LINE to enable/disable Weather:
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/weather-stubs.yaml]        # ← DISABLED
    # files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/weather-ha-actions.yaml]  # ← Enable this for Weather
    refresh: always

  pkg_wireguard:
    url: https://github.com/truffshuff/halo.git
    ref: main
    # CHANGE THIS LINE to enable/disable WireGuard:
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/wireguard-stubs.yaml]  # ← DISABLED
    # files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/wireguard.yaml]       # ← Enable this for WireGuard
    refresh: always

  pkg_pages:
    url: https://github.com/truffshuff/halo.git
    ref: main
    # CHANGE THIS LINE to match your enabled features:
    files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/lvgl-pages-clock-only.yaml]  # ← Clock only
    # Other options (uncomment ONE):
    # files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/lvgl-pages-airq-only.yaml]
    # files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/lvgl-pages-wifi-only.yaml]
    # files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/lvgl-pages-weather-forecast-only.yaml]
    # files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/lvgl-pages-airq-wifi.yaml]
    # files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/lvgl-pages-airq-weather-forecast-only.yaml]
    # files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/lvgl-pages-wifi-weather-forecast-only.yaml]
    # files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/lvgl-pages-airq-wifi-weather-forecast.yaml]
    refresh: always

# ============================================================================
# CORE CONFIGURATION (inlined from Halo-v1-Core.yaml)
# ============================================================================
# Since we can't load Halo-v1-Core.yaml from GitHub (nested packages issue),
# we inline the essential configuration here.

psram:
  mode: octal
  speed: 80MHz

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_SPIRAM_USE: "y"
      CONFIG_SPIRAM_MODE_OCT: "y"
      CONFIG_SPIRAM_SPEED_80M: "y"
      CONFIG_SPIRAM_USE_MALLOC: "y"
      CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL: "4096"
      CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_EXTERNAL: "y"
      CONFIG_BT_NIMBLE_USE_ESP_TIMER: "y"
      CONFIG_BT_NIMBLE_MAX_CONNECTIONS: "4"
      CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE: "8192"
      CONFIG_LWIP_TCPIP_RECVMBOX_SIZE: "64"
      CONFIG_LWIP_TCP_RECVMBOX_SIZE: "24"
      CONFIG_LWIP_UDP_RECVMBOX_SIZE: "24"
      CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY: "y"
      CONFIG_LV_MEM_CUSTOM: "y"
      CONFIG_LV_MEM_CUSTOM_ALLOC_EXTERNAL: "y"
      CONFIG_LV_MEM_SIZE: "262144"
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"
      CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM: "16"
      CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM: "32"
      CONFIG_ESP_WIFI_DYNAMIC_TX_BUFFER_NUM: "32"
      CONFIG_ESP_WIFI_RX_BA_WIN: "32"
      CONFIG_ESP_WIFI_TX_BA_WIN: "32"
      CONFIG_ESP_WIFI_RX_MGMT_BUF_NUM: "32"
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "12"
      CONFIG_FREERTOS_IDLE_TASK_STACKSIZE: "4096"
      CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL: "16384"
      CONFIG_ESP_MAIN_TASK_STACK_SIZE: "12288"
      CONFIG_FREERTOS_THREAD_LOCAL_STORAGE_POINTERS: "2"
      CONFIG_FREERTOS_USE_STATIC_TASK_CLEAN_UP: "y"
      CONFIG_LWIP_MAX_SOCKETS: "24"
      CONFIG_LWIP_SO_RCVBUF: "y"
      CONFIG_LWIP_SO_RCVBUF_DEFAULT: "8192"
      CONFIG_TCP_MAXRTX: "16"
      CONFIG_TCP_SYNMAXRTX: "8"
      CONFIG_HEAP_TRACING_STANDALONE: "y"
      CONFIG_HEAP_TRACING: "y"
      CONFIG_HEAP_TASK_TRACKING: "y"
      CONFIG_HEAP_POISONING_LIGHT: "y"
      CONFIG_ESP_SYSTEM_MEMPROT_FEATURE: "n"

external_components:
  - source: github://truffshuff/esphome-components
    components: [axs15231, sy6970]

spi:
  id: lily_spi
  type: quad
  clk_pin: 17
  data_pins: [13, 18, 21, 14]

captive_portal:

logger:
  level: INFO

esphome:
  name: ${name}
  on_boot:
    - priority: 800
      then:
        - delay: 50ms
        - lvgl.page.show: vertical_clock_page
        - logger.log: "Set initial page to Vertical Clock"
    - priority: -100
      then:
        - logger.log: "Boot sequence starting"
        # Note: RGB light turn-off removed to avoid package loading order issues
        # The startup_light_blink interval handles RGB light control
        - delay: 1s
        - lambda: |-
            const std::string &choice = id(default_page_select_boot).state;
            if (choice == "Vertical Clock") {
              id(default_page_index) = 0;
            } else if (choice == "AirQ") {
              id(default_page_index) = 1;
            } else if (choice == "WiFi") {
              id(default_page_index) = 2;
            } else if (choice == "Weather") {
              id(default_page_index) = 3;
            } else {
              id(default_page_index) = 0;
            }
        - lvgl.page.show: vertical_clock_page

# (Rest of core config - globals, switches, selects, intervals, etc.)
# See Halo-v1-Core.yaml for full configuration
# This is abbreviated for brevity - you would need to copy ALL sections

# WiFi credentials
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap:
    ssid: "Halo-79e384-Fallback"
    password: "fallback12345"

# OTA
ota:
  - platform: esphome
    password: ${ota_password}

# Default page selector
select:
  - platform: template
    name: "Default Page at Boot"
    id: default_page_select_boot
    optimistic: true
    options:
      - "Vertical Clock"
    initial_option: "Vertical Clock"
    restore_value: true

# ============================================================================
# NOTES
# ============================================================================
#
# This version loads packages from GitHub but requires:
# 1. Manually editing file paths to enable/disable features
# 2. Copying ALL core configuration inline (can't use Halo-v1-Core.yaml)
# 3. Remember to update time_update package when enabling/disabling AirQ
#
# EASIER ALTERNATIVE: Copy files to /config/esphome/ and use !include
# See: halo-v1-79e384-ha-manual.yaml
#
# ============================================================================
