# ============================================================================
# Halo V1 - Dynamic Configuration Template (ESPHome 2025.10.0+)
# ============================================================================
# This template uses ESPHome 2025.10.0's dynamic auto-loading feature with
# substitutions to enable/disable features via simple TRUE/FALSE flags.
#
# 🚀 NEW IN THIS VERSION:
#   - Feature flags instead of commenting/uncommenting packages
#   - Weather via Home Assistant Actions (on-demand, ~70KB RAM savings!)
#   - ESPHome 2025.10.0 optimizations (~1-2KB additional savings)
#   - Simplified configuration management
#
# ✅ BLE + FULL WEATHER NOW POSSIBLE!
#   Old approach: BLE (60KB) + Weather sensors (75KB) = Too tight!
#   New approach: BLE (60KB) + HA Actions (3KB) = Plenty of room!
#
# 🎛️ CONFIGURATION:
#   Simply change the feature flags below from "false" to "true" to enable
#   features. No more commenting/uncommenting packages!
# ============================================================================

# ============================================================================
# FEATURE FLAGS - Enable/Disable Features
# ============================================================================
substitutions:
  # Device Configuration
  name: "halo-v1-yourname"  # CHANGE THIS
  friendly_name: "Halo V1"

  # Display Features
  feature_clock: "true"              # Always true (core feature)
  feature_airq: "false"              # Air quality display page
  feature_wifi_page: "false"         # WiFi info display page
  feature_wireguard: "false"         # WireGuard VPN (requires wifi_page)

  # Weather Features (NEW - uses HA Actions!)
  feature_weather: "false"           # Enable weather via HA actions
  weather_entity_id: "weather.home"  # Your HA weather entity
  weather_refresh_interval: "300"    # Seconds (5 min default)

  # Connectivity Features
  feature_ble: "false"               # BLE presence detection

  # Memory Management
  feature_psram_optimization: "true" # Keep enabled for best performance
  feature_memory_stats: "true"       # Show memory usage stats

  # Network Configuration (fill these in if using WiFi)
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  # API Configuration
  api_encryption_key: !secret api_encryption_key
  ota_password: !secret ota_password

# ============================================================================
# ESPHOME CONFIGURATION
# ============================================================================
esphome:
  name: ${name}
  friendly_name: ${friendly_name}

  # Optimized for ESP32-S3
  platformio_options:
    board_build.flash_mode: dio
    board_build.psram_type: opi
    build_flags:
      # PSRAM optimizations for memory-intensive features
      - "-DBOARD_HAS_PSRAM"
      - "-DCONFIG_SPIRAM_CACHE_WORKAROUND"
      # Display buffer optimization (use 15% for BLE compatibility)
      - "-DLVGL_BUFFER_SIZE_PERCENTAGE=15"

  on_boot:
    - priority: 800
      then:
        - delay: 50ms
        - lvgl.page.show: vertical_clock_page
        - logger.log: "Set initial page to Vertical Clock"

# ============================================================================
# ESP32 HARDWARE CONFIGURATION
# ============================================================================
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      # PSRAM Configuration
      CONFIG_SPIRAM_MODE_OCT: y
      CONFIG_SPIRAM_SPEED_80M: y
      CONFIG_SPIRAM: y
      CONFIG_ESP32S3_SPIRAM_SUPPORT: y
      CONFIG_SPIRAM_USE_MALLOC: y
      CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL: "16384"
      CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL: "65536"

      # LVGL optimizations
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: n
      CONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY: y
      CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY: n

      # BLE Coexistence tuning (if BLE enabled)
      CONFIG_BTDM_CTRL_BLE_MAX_CONN: "3"
      CONFIG_BTDM_CTRL_BLE_MAX_CONN_EFF: "3"

# ============================================================================
# CORE SERVICES
# ============================================================================

# Logger
logger:
  level: INFO
  logs:
    component: ERROR

# API
api:
  encryption:
    key: ${api_encryption_key}

# OTA Updates
ota:
  - platform: esphome
    password: ${ota_password}

# WiFi (conditionally enabled if any network feature is true)
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  # Fallback AP mode
  ap:
    ssid: "${friendly_name} Fallback"
    password: "fallback12345"

# Captive portal for easy WiFi setup
captive_portal:

# Web server (optional, comment out if not needed)
# web_server:
#   port: 80

# ============================================================================
# PACKAGE IMPORTS - Core Functionality
# ============================================================================
packages:
  # Core device configuration (always required)
  halo_core:
    url: https://github.com/truffshuff/halo.git/
    ref: main
    files:
      - TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/Halo-v1-Core.yaml
    refresh: always

  # PSRAM optimization helpers (conditional)
  psram_helpers:
    url: https://github.com/truffshuff/halo.git/
    ref: main
    files:
      - TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/psram-helpers.yaml
    refresh: always
    # Only load if PSRAM optimization is enabled
    # NOTE: ESPHome 2025.10.0 dynamic auto-loading syntax (may need adjustment)
    # For now, uncomment/comment this entire section to enable/disable

  # Memory statistics (conditional)
  # memory_stats:
  #   url: https://github.com/truffshuff/halo.git/
  #   ref: main
  #   files:
  #     - TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/memory-stats.yaml
  #   refresh: always

# ============================================================================
# FEATURE PACKAGES - Enable via Feature Flags
# ============================================================================

# ----------------------------------------------------------------------------
# BLE PRESENCE DETECTION (feature_ble)
# ----------------------------------------------------------------------------
# Uncomment this section if feature_ble = "true"
# ble_core:
#   url: https://github.com/truffshuff/halo.git/
#   ref: main
#   files:
#     - TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/ble-core-simplified.yaml
#   refresh: always

# ----------------------------------------------------------------------------
# WEATHER VIA HOME ASSISTANT ACTIONS (feature_weather)
# ----------------------------------------------------------------------------
# Uncomment this section if feature_weather = "true"
# weather_ha_actions:
#   url: https://github.com/truffshuff/halo.git/
#   ref: main
#   files:
#     - TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/weather-ha-actions.yaml
#   refresh: always

# Also need weather core and fonts:
# weather_core:
#   url: https://github.com/truffshuff/halo.git/
#   ref: main
#   files:
#     - TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/weather-core.yaml
#   refresh: always

# weather_fonts:
#   url: https://github.com/truffshuff/halo.git/
#   ref: main
#   files:
#     - TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/weather-fonts-text.yaml
#   refresh: always

# ----------------------------------------------------------------------------
# AIR QUALITY DISPLAY (feature_airq)
# ----------------------------------------------------------------------------
# Uncomment this section if feature_airq = "true"
# airq_package:
#   url: https://github.com/truffshuff/halo.git/
#   ref: main
#   files:
#     - TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/airq-display.yaml
#   refresh: always

# ----------------------------------------------------------------------------
# WIREGUARD VPN (feature_wireguard)
# ----------------------------------------------------------------------------
# Uncomment this section if feature_wireguard = "true"
# wireguard_package:
#   url: https://github.com/truffshuff/halo.git/
#   ref: main
#   files:
#     - TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/wireguard.yaml
#   refresh: always

# ============================================================================
# LVGL PAGES - Select Based on Enabled Features
# ============================================================================
# Choose the pages package that matches your enabled features
#
# DECISION MATRIX:
# Clock-only configs:
#   - lvgl-pages-clock-only.yaml               feature_clock only
#
# Clock + one feature:
#   - lvgl-pages-airq-only.yaml                + feature_airq
#   - lvgl-pages-wifi-only.yaml                + feature_wifi_page
#   - lvgl-pages-wifi-wireguard.yaml           + feature_wifi_page + feature_wireguard
#   - lvgl-pages-weather-forecast-only.yaml    + feature_weather (BLE compatible!)
#
# Clock + multiple features (NO BLE - too much memory):
#   - lvgl-pages-airq-wifi.yaml                + airq + wifi
#   - lvgl-pages-airq-weather-forecast-only.yaml  + airq + weather
#   - lvgl-pages-wifi-weather-forecast-only.yaml  + wifi + weather
#   - lvgl-pages-airq-wifi-weather-forecast.yaml  + airq + wifi + weather
#   - lvgl-pages-full.yaml                     + airq + wifi + weather (full)
#   - lvgl-pages-full-wireguard.yaml           + airq + wifi + wireguard + weather (full)

# EXAMPLE: Clock + Weather only (BLE compatible!)
# lvgl_pages:
#   url: https://github.com/truffshuff/halo.git/
#   ref: main
#   files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/lvgl-pages-weather-forecast-only.yaml]
#   refresh: always

# For now, default to clock only
lvgl_pages:
  url: https://github.com/truffshuff/halo.git/
  ref: main
  files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/lvgl-pages-clock-only.yaml]
  refresh: always

# ============================================================================
# DEFAULT PAGE SELECTOR
# ============================================================================
# Update options to match your enabled pages
select:
  - platform: template
    name: "Default Page at Boot"
    id: default_page_select_boot
    optimistic: true
    options:
      - "Vertical Clock"
      # Add options based on enabled features:
      # - "AirQ"          # if feature_airq
      # - "WiFi"          # if feature_wifi_page
      # - "Weather"       # if feature_weather
    initial_option: "Vertical Clock"
    restore_value: true

# ============================================================================
# CONFIGURATION GUIDE
# ============================================================================
# STEP 1: Set your feature flags at the top of this file
# STEP 2: Uncomment the corresponding package sections above
# STEP 3: Choose the correct lvgl_pages package
# STEP 4: Update the default_page_select_boot options
# STEP 5: Compile and flash!
#
# MEMORY BUDGET GUIDE (ESP32-S3 has ~210KB internal RAM):
# ✅ BLE Compatible (< 110KB total):
#    - Clock only: ~45KB
#    - Clock + AirQ: ~65KB
#    - Clock + WiFi: ~85KB
#    - Clock + Weather (HA Actions): ~105KB ← NEW! BLE compatible!
#
# ⚠️ NOT BLE Compatible (> 110KB total):
#    - Clock + AirQ + WiFi: ~125KB
#    - Clock + AirQ + Weather: ~130KB
#    - Clock + WiFi + Weather: ~135KB
#    - Clock + AirQ + WiFi + Weather: ~140KB
#
# With the new HA Actions approach, you can have Clock + Weather + BLE
# which was previously impossible!
# ============================================================================

# ============================================================================
# MIGRATION NOTES FROM OLD SENSOR-BASED WEATHER
# ============================================================================
# If you're migrating from weather-sensors-*.yaml packages:
#
# 1. Remove old weather sensor packages:
#    - weather-sensors-current.yaml
#    - weather-sensors-daily.yaml
#    - weather-sensors-hourly.yaml
#
# 2. Add the new weather-ha-actions.yaml package
#
# 3. Update your weather page YAML files to use the new globals:
#    OLD: id(forecast_day1_high_temp).state
#    NEW: id(weather_forecast_temp_high)[0]
#
# 4. Add page tracking to weather pages:
#    on_load: lambda: 'id(weather_on_weather_page) = true;'
#
# 5. The weather-ha-actions.yaml file includes a template for updating
#    displays - customize it for your label IDs
#
# Memory savings: ~70KB! This enables BLE + Weather coexistence!
# ============================================================================
