# Your Wi-Fi SSID and password
wifi_ssid: "iPhoneDW"
wifi_password: "ianianian"
my_alt_ssid: "iPhoneD13"
my_alt_password: "519519519519"
wifihome_ssid: "YourMom15;)"
wifihome_password: "519519519519"


#Wireguard Stuff
wg_address: 10.6.0.2
wg_netmask: 0.0.0.0
wg_peerport: 51820
wg_prikey: gFrKaUf1j2DTDmO1gD32op15t3JNAz1W8MVw9GdtBm4=
wg_pubkey: OHSVnpenK/ZQauqbjF9sbaqq55yKI8oDGJRfIDZLBns=
wg_shrdkey: cP9tEJU+AjQcCj993ChLsoYxQd5e3PAIrlN3w1kpaQs=
wg_peerendpt: 73.86.51.45

#MQTT
mqtt_user: "hhutmqttesp2"
mqtt_pass: "esp2mqtthhut"

#HALO Token
ha_api_token: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzODQxODNlOWY5YjY0Y2NhOTFlNjUzMjNiZDkyODZjNyIsImlhdCI6MTc2MDcwNzA0MywiZXhwIjoyMDc2MDY3MDQzfQ.rxulRd8unYyqNl6mCC5Cvry9iovMcujXsPzTPy9t11w"

# Security
api_encryption_key: "mLKXHYyBZgGLfMiXyWoo3Fzc/TpqbKpk0g+uYAwErMs="
ota_password: "halo79e384"