# ============================================================================
# AirQ Stubs Package - Stub Globals for AirQ-Disabled Mode
# ============================================================================
# This package provides stub globals for when AirQ monitoring is disabled.
# It prevents compilation errors in page rotation logic by defining the
# required globals with disabled/neutral values.
#
# Usage:
#   1. Comment out airq-core.yaml and airq-display.yaml in main config
#   2. Include this package instead: airq_stubs: !include packages/airq-stubs.yaml
#   3. Comment out airq-display.yaml in the lvgl pages section
#   4. The firmware will compile without AirQ features
#
# IMPORTANT LIMITATIONS when AirQ is disabled:
#   - LED Effects: "AQI Color" should NOT appear in the LED Effect selector
#     If it does appear, DO NOT select it - it requires the AirQ sensors
#   - If selected, LEDs will remain off (safe fallback)
#   - Recommended: Use "Rainbow Effect", "Color Wipe", or other effects instead
#
# Note: Similar pattern to weather-stubs.yaml for optional weather features
# ============================================================================

globals:
  # Page rotation settings - which pages are included
  - id: page_rotation_AirQ_enabled
    type: bool
    restore_value: no
    initial_value: 'false'

  - id: page_rotation_AirQ_order
    type: int
    restore_value: no
    initial_value: '99'

# Stub sensor to prevent compilation errors in LED effect logic
sensor:
  - platform: template
    name: "Computed AQI (Stub)"
    id: computed_halo_aqi
    internal: true
    update_interval: never
    accuracy_decimals: 0
    lambda: 'return NAN;'  # Always return NaN (not a number)

# Stub text_sensor to satisfy time_update script references
# The time_update script tries to update timeVal label on AirQ page
# We can't add LVGL objs in a package (they don't merge properly)
# Instead, we provide a dummy text_sensor that satisfies the ID requirement
# The actual timeVal label will come from the pages package
text_sensor:
  - platform: template
    name: "Time Value (Stub)"
    id: timeVal_stub
    internal: true
    update_interval: never

# Note: The actual timeVal label must be defined in your LVGL pages package
# If using clock-only, it won't have timeVal, so the time_update script
# will try to update a non-existent label, but won't crash (just log warning)