# ============================================================================
# AirQ Stubs Package - Stub Globals for AirQ-Disabled Mode
# ============================================================================
# This package provides stub globals for when AirQ monitoring is disabled.
# It prevents compilation errors in page rotation logic by defining the
# required globals with disabled/neutral values.
#
# Usage:
#   1. Comment out airq-core.yaml and airq-display.yaml in main config
#   2. Include this package instead: airq_stubs: !include packages/airq-stubs.yaml
#   3. Comment out airq-display.yaml in the lvgl pages section
#   4. The firmware will compile without AirQ features
#
# IMPORTANT LIMITATIONS when AirQ is disabled:
#   - LED Effects: Do NOT select "AQI Color" or "Auto Context" effects
#     These depend on computed_halo_aqi sensor which won't exist
#   - If selected, LEDs will remain off (safe fallback)
#   - Recommended: Use "Rainbow Effect", "Color Wipe", or other effects
#
# Note: Similar pattern to weather-stubs.yaml for optional weather features
# ============================================================================

globals:
  # Page rotation settings - which pages are included
  - id: page_rotation_AirQ_enabled
    type: bool
    restore_value: no
    initial_value: 'false'
  
  - id: page_rotation_AirQ_order
    type: int
    restore_value: no
    initial_value: '99'