# AirQ Page Definition
# This file defines the LVGL page layout for the AirQ monitoring page
# It is included by lvgl-pages-*.yaml files as a page definition
id: AirQ_page
bg_color: my_black
scrollbar_mode: "OFF"
on_load:
  - script.execute: page_transition_cleanup
  - lambda: |-
      id(current_page_index) = 1;  // AirQ_page
      id(time_update_last_text).clear();
  - script.execute: time_update
  # Immediately update WiFi indicator when page loads
  - if:
      condition:
        wifi.connected:
      then:
        - lvgl.widget.update:
            id: wifi_stat
            text_color: my_green
        - lambda: 'id(wifi_stat_connected_state) = true;'
      else:
        - lvgl.widget.update:
            id: wifi_stat
            text_color: my_red
        - lambda: 'id(wifi_stat_connected_state) = false;'
widgets:
  # Header: Logo, Time, WiFi Status
  - image:
      id: ym_image
      src: ym_logo
      align: CENTER
      x: 80
      y: -309
  - label:
      id: timeVal
      align: LEFT_MID
      text_font: montserrat_18
      text_color: my_white
      x: 2
      y: -309
      text: "00:00AM"
  - label:
      id: wifi_stat
      align: CENTER
      text_font: montserrat_18
      text_color: my_gray
      x: 42
      y: -309
      text: "\uF1EB"

  # AQI Widget (Color-coded banner)
  - obj:
      id: aqi_widget
      x: 0
      y: 24
      width: 180
      height: 42
      bg_color: 0x76fa76
      border_width: 0
  - label:
      id: aqi_label
      align: LEFT_MID
      text_font: montserrat_28
      text_color: my_black
      long_mode: WRAP
      x: 2
      y: -275
      text: "AQI:"
  - label:
      id: aqi_value
      align: LEFT_MID
      text_font: montserrat_28
      text_color: my_black
      long_mode: WRAP
      x: 90
      y: -275
      text: "000"

  # Temperature Section
  - label:
      id: temperature_label
      align: LEFT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: 2
      y: -246
      text: "TEMP:"
  - label:
      id: temperature_value
      align: CENTER
      text_font: montserrat_28
      text_color: my_white
      long_mode: WRAP
      x: 0
      y: -234
      text: "000.0"
  - label:
      id: temperature_units
      align: RIGHT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: -8
      y: -234
      text: "\u00B0F"
  - line:
      points:
        - 0, 106
        - 180, 106
      line_width: 1
      line_color: 0x00dfff

  # CO2 Section
  - label:
      id: co2_label
      align: LEFT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: 2
      y: -205
      text: "CO2:"
  - label:
      id: co2_value
      align: CENTER
      text_font: montserrat_28
      text_color: my_white
      long_mode: WRAP
      x: 0
      y: -193
      text: "0000"
  - label:
      id: co2_units
      align: RIGHT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: -2
      y: -193
      text: "PPM"
  - line:
      points:
        - 0, 147
        - 180, 147
      line_width: 1
      line_color: 0x00dfff

  # PM1.0 Section
  - label:
      id: pm1_label
      align: LEFT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: 2
      y: -164
      text: "PM1:"
  - label:
      id: pm1_value
      align: RIGHT_MID
      text_font: montserrat_28
      text_color: my_white
      long_mode: WRAP
      x: -51
      y: -152
      text: "000.0"
  - label:
      id: pm1_units
      align: RIGHT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: -2
      y: -152
      text: "ug/m3"
  - line:
      points:
        - 0, 188
        - 180, 188
      line_width: 1
      line_color: 0x00dfff

  # PM2.5 Section
  - label:
      id: pm25_label
      align: LEFT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: 2
      y: -123
      text: "PM2.5:"
  - label:
      id: pm25_value
      align: RIGHT_MID
      text_font: montserrat_28
      text_color: my_white
      long_mode: WRAP
      x: -51
      y: -111
      text: "000.0"
  - label:
      id: pm25_units
      align: RIGHT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: -2
      y: -111
      text: "ug/m3"
  - line:
      points:
        - 0, 229
        - 180, 229
      line_width: 1
      line_color: 0x00dfff

  # PM4.0 Section
  - label:
      id: pm4_label
      align: LEFT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: 2
      y: -82
      text: "PM4:"
  - label:
      id: pm4_value
      align: RIGHT_MID
      text_font: montserrat_28
      text_color: my_white
      long_mode: WRAP
      x: -51
      y: -70
      text: "000.0"
  - label:
      id: pm4_units
      align: RIGHT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: -2
      y: -70
      text: "ug/m3"
  - line:
      points:
        - 0, 270
        - 180, 270
      line_width: 1
      line_color: 0x00dfff

  # PM10 Section
  - label:
      id: pm10_label
      align: LEFT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: 2
      y: -41
      text: "PM10:"
  - label:
      id: pm10_value
      align: RIGHT_MID
      text_font: montserrat_28
      text_color: my_white
      long_mode: WRAP
      x: -51
      y: -29
      text: "000.0"
  - label:
      id: pm10_units
      align: RIGHT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: -2
      y: -29
      text: "ug/m3"
  - line:
      points:
        - 0, 311
        - 180, 311
      line_width: 1
      line_color: 0x00dfff

  # VOC Section
  - label:
      id: voc_label
      align: LEFT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: 2
      y: 0
      text: "VOC:"
  - label:
      id: voc_value
      align: RIGHT_MID
      text_font: montserrat_28
      text_color: my_white
      long_mode: WRAP
      x: -51
      y: 12
      text: "000.0"
  - label:
      id: voc_units
      align: RIGHT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: -2
      y: 12
      text: "IDX"
  - line:
      points:
        - 0, 352
        - 180, 352
      line_width: 1
      line_color: 0x00dfff

  # CO Section
  - label:
      id: co_label
      align: LEFT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: 2
      y: 41
      text: "CO:"
  - label:
      id: co_value
      align: RIGHT_MID
      text_font: montserrat_28
      text_color: my_white
      long_mode: WRAP
      x: -51
      y: 53
      text: "000.0"
  - label:
      id: co_units
      align: RIGHT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: -2
      y: 53
      text: "PPM"
  - line:
      points:
        - 0, 393
        - 180, 393
      line_width: 1
      line_color: 0x00dfff

  # Ethanol Section
  - label:
      id: ethanol_label
      align: LEFT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: SCROLL
      width: 40
      x: 2
      y: 82
      text: "C2H5OH:"
  - label:
      id: ethanol_value
      align: RIGHT_MID
      text_font: montserrat_28
      text_color: my_white
      long_mode: WRAP
      x: -51
      y: 94
      text: "000.0"
  - label:
      id: ethanol_units
      align: RIGHT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: -2
      y: 94
      text: "PPM"
  - line:
      points:
        - 0, 434
        - 180, 434
      line_width: 1
      line_color: 0x00dfff

  # Hydrogen Section
  - label:
      id: h2_label
      align: LEFT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: 2
      y: 124
      text: "H2:"
  - label:
      id: h2_value
      align: RIGHT_MID
      text_font: montserrat_28
      text_color: my_white
      long_mode: WRAP
      x: -51
      y: 135
      text: "000.0"
  - label:
      id: h2_units
      align: RIGHT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: -2
      y: 135
      text: "PPM"
  - line:
      points:
        - 0, 475
        - 180, 475
      line_width: 1
      line_color: 0x00dfff

  # NO2 Section
  - label:
      id: no2_label
      align: LEFT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: 2
      y: 165
      text: "NO2:"
  - label:
      id: no2_value
      align: RIGHT_MID
      text_font: montserrat_28
      text_color: my_white
      long_mode: WRAP
      x: -51
      y: 176
      text: "000.0"
  - label:
      id: no2_units
      align: RIGHT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: -2
      y: 176
      text: "PPM"
  - line:
      points:
        - 0, 516
        - 180, 516
      line_width: 1
      line_color: 0x00dfff

  # NH3 Section
  - label:
      id: nh3_label
      align: LEFT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: 2
      y: 206
      text: "NH3:"
  - label:
      id: nh3_value
      align: RIGHT_MID
      text_font: montserrat_28
      text_color: my_white
      long_mode: WRAP
      x: -51
      y: 217
      text: "000.0"
  - label:
      id: nh3_units
      align: RIGHT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: -2
      y: 217
      text: "PPM"
  - line:
      points:
        - 0, 557
        - 180, 557
      line_width: 1
      line_color: 0x00dfff

  # CH4 Section
  - label:
      id: ch4_label
      align: LEFT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: 2
      y: 247
      text: "CH4:"
  - label:
      id: ch4_value
      align: RIGHT_MID
      text_font: montserrat_28
      text_color: my_white
      long_mode: WRAP
      x: -51
      y: 258
      text: "000.0"
  - label:
      id: ch4_units
      align: RIGHT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: -2
      y: 258
      text: "PPM"
  - line:
      points:
        - 0, 598
        - 180, 598
      line_width: 1
      line_color: 0x00dfff

  # RH (Relative Humidity) Section
  - label:
      id: rh_label
      align: LEFT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: 2
      y: 287
      text: "RH:"
  - label:
      id: rh_value
      align: RIGHT_MID
      text_font: montserrat_28
      text_color: my_white
      long_mode: WRAP
      x: -51
      y: 299
      text: "000.0"
  - label:
      id: rh_units
      align: RIGHT_MID
      text_font: montserrat_14
      text_color: my_white
      long_mode: WRAP
      x: -2
      y: 299
      text: "%"

  # Navigation Button (top-right corner touch area)
  - obj:
      id: nav_button_AirQ
      align: TOP_RIGHT
      x: 0
      y: 0
      width: 100
      height: 100
      bg_opa: 0
      border_width: 0
      clickable: true
      on_press:
        - logger.log: "AirQ page nav button PRESSED!"
        - lambda: |-
            ESP_LOGI("touch", "Navigation button touched");
            id(last_auto_rotation_time) = millis();
            ESP_LOGD("touch", "Auto-rotation timer reset");
        - lvgl.page.next:
            animation: OUT_LEFT
            time: 300ms
