# BLE Coexistence Tuning
# Apply conservative LVGL/Logger settings when BLE is enabled to reduce heap

substitutions:
  lvgl_buffer_percent_with_ble: "20%"  # 15-20% recommended when BLE active
  logger_level_with_ble: "WARN"        # Reduce log noise/allocations

logger:
  level: ${logger_level_with_ble}

# Reduce LVGL buffer usage to free internal heap for BLE
lvgl:
  buffer_size: ${lvgl_buffer_percent_with_ble}

text_sensor:
  - platform: template
    name: "BLE Coexist Tuning"
    entity_category: diagnostic
    lambda: |-
      char buf[64];
      snprintf(buf, sizeof(buf), "LVGL %s, Log %s", "${lvgl_buffer_percent_with_ble}", "${logger_level_with_ble}");
      return std::string(buf);
    update_interval: 120s
