# ============================================================================
# BLE Core Package - DELAYED SCANNING
# ============================================================================
# This package contains BLE scanner and Bluetooth Proxy with DELAYED scanning.
#
# IMPORTANT: BLE stack ALWAYS initializes at boot and allocates 80-100KB.
# This is unavoidable in ESPHome. To make room for BLE:
#   - Reduce LVGL buffer_size to 20% (saves ~45KB)
#   - PSRAM optimization saves another ~70KB during runtime
#
# WHY DELAYED SCANNING (not initialization)?
#   - BLE stack initializes at boot (can't prevent this)
#   - But we delay SCANNING by 10 seconds
#   - This gives weather sensors time to connect and receive data
#   - PSRAM moves sensor buffers, freeing heap for BLE operations
#
# MEMORY TIMELINE:
#   Boot (0s)      → 80KB free (with LVGL at 20%)
#   BLE init (0s)  → BLE stack allocates 80KB
#   Sensors (1-5s) → Sensors connect, using internal heap
#   PSRAM (5-8s)   → Sensors moved to PSRAM, 70KB freed
#   Scan (10s)     → BLE scanning starts with 70KB extra headroom
#
# ============================================================================

# Global flag to track if BLE scanning should be auto-started
globals:
  - id: ble_delayed_start_enabled
    type: bool
    restore_value: no
    initial_value: 'true'

# ESP32 BLE Tracker Configuration
# NOTE: BLE stack initializes at boot (unavoidable)
# We just delay when SCANNING starts
esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    interval: 500ms
    window: 40ms
    active: true
    continuous: false

# Bluetooth Proxy Configuration
bluetooth_proxy:
  active: true
  connection_slots: 3

# ESP32 Improv Configuration  
esp32_improv:
  authorizer: none

# Delayed BLE SCANNING (not initialization)
# Wait 10 seconds after boot to allow PSRAM optimization to free up memory
esphome:
  on_boot:
    - priority: -100  # Run after almost everything else
      then:
        - logger.log:
            format: "BLE delayed scan: Waiting 10 seconds for PSRAM optimization..."
            level: INFO
        - delay: 10s
        - logger.log:
            format: "BLE delayed scan: Checking memory before starting scanning..."
            level: INFO
        - lambda: |-
            size_t free_heap = heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
            ESP_LOGI("ble_delayed", "Free internal heap: %d bytes", free_heap);
            if (free_heap >= 50000) {
              ESP_LOGI("ble_delayed", "✓ Good memory headroom, starting BLE scan...");
            } else if (free_heap >= 28000) {
              ESP_LOGI("ble_delayed", "✓ Minimum memory available, starting BLE scan...");
            } else {
              ESP_LOGW("ble_delayed", "⚠ Only %dKB free, BLE may be unstable", free_heap / 1024);
            }
        - if:
            condition:
              lambda: 'return id(ble_delayed_start_enabled);'
            then:
              - logger.log:
                  format: "BLE delayed scan: Starting BLE scanner..."
                  level: INFO
              - esp32_ble_tracker.start_scan:
                  continuous: false
              - logger.log:
                  format: "✓ BLE scanner started successfully!"
                  level: INFO

# API Integration - Dynamic BLE Scanning
# Start/stop BLE scanning based on Home Assistant connection
# NOTE: This will work even with delayed start since it checks connection state
api:
  on_client_connected:
    - delay: 500ms
    - logger.log:
        format: "Home Assistant connected, starting BLE scan..."
        level: INFO
    - esp32_ble_tracker.start_scan:
        continuous: true

  on_client_disconnected:
    - logger.log:
        format: "Home Assistant disconnected, stopping BLE scan..."
        level: INFO
    - esp32_ble_tracker.stop_scan:

# Manual BLE control buttons (optional - for debugging)
# You can expose these to Home Assistant to manually control BLE
button:
  - platform: template
    name: "Start BLE Scanning"
    id: btn_start_ble
    entity_category: diagnostic
    on_press:
      - logger.log: "Manual BLE start requested"
      - esp32_ble_tracker.start_scan:
          continuous: false

  - platform: template
    name: "Stop BLE Scanning"
    id: btn_stop_ble
    entity_category: diagnostic
    on_press:
      - logger.log: "Manual BLE stop requested"
      - esp32_ble_tracker.stop_scan:

# Memory monitoring - check if we have enough heap for BLE
sensor:
  - platform: template
    name: "BLE Memory Check"
    id: ble_memory_check
    lambda: |-
      size_t free_heap = heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
      // Return 1 if enough memory for BLE, 0 if not
      return (free_heap >= 80000) ? 1.0 : 0.0;
    update_interval: 30s
    entity_category: diagnostic

# Status text sensor showing BLE readiness
text_sensor:
  - platform: template
    name: "BLE Status"
    id: ble_status
    lambda: |-
      size_t free_heap = heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
      if (free_heap >= 100000) {
        return {"Ready (Plenty of memory)"};
      } else if (free_heap >= 80000) {
        return {"Ready (Minimum memory)"};
      } else {
        char status[64];
        snprintf(status, sizeof(status), "Low Memory (%dKB free, need 80KB)", free_heap / 1024);
        return {status};
      }
    update_interval: 30s
    entity_category: diagnostic
