# ============================================================================
# BLE Core Package - Bluetooth Low Energy Tracker and Proxy
# ============================================================================
# This package contains BLE scanner and Bluetooth Proxy functionality.
#
# Included Components:
#   - ESP32 BLE Tracker (required for Bluetooth Proxy)
#   - Bluetooth Proxy (Home Assistant integration)
#   - ESP32 Improv (WiFi provisioning via BLE)
#
# Dependencies:
#   - ESP32 platform with BLE support
#   - Sufficient heap memory (can cause OOM if other features enabled)
#
# Performance Impact:
#   - Memory: ~50-80KB heap usage (can exhaust heap with display features)
#   - CPU: Moderate - BLE scanning is CPU intensive
#   - Battery: High - continuous BLE scanning drains power
#
# IMPORTANT NOTES:
#   - Bluetooth Proxy REQUIRES esp32_ble_tracker to function
#   - BLE features are DISABLED by default due to heap exhaustion issues
#   - Enabling BLE may cause crashes if combined with:
#     - Large LVGL display configurations
#     - Multiple sensors on I2C/SPI
#     - WiFi + WireGuard simultaneously
#   - Test thoroughly after enabling BLE features
#
# Recommended Configuration:
#   - Disable BLE if using full display + sensors (default)
#   - Enable only if you need Home Assistant Bluetooth Proxy
#   - Monitor heap usage via memory_stats package
#   - Consider reducing LVGL buffer_size if enabling BLE
# ============================================================================

# ESP32 BLE Tracker Configuration
# This component is REQUIRED for bluetooth_proxy to work
# Scans for BLE devices and makes them available to Home Assistant
esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    # Scan interval - how often to scan for devices
    # Default: 320ms, Balanced: 500ms, Always-on: 1100ms
    interval: 500ms

    # Scan window - how long each scan lasts
    # Default: 30ms, Balanced: 40ms, Always-on: 1100ms
    window: 40ms

    # Active scanning - sends scan requests to get more device info
    # true = more info but higher power consumption
    # false = passive scanning, lower power
    active: true

    # Continuous scanning mode
    # true = constant scanning (high power, immediate detection)
    # false = on-demand scanning (lower power, delayed detection)
    continuous: false

# Bluetooth Proxy Configuration
# Allows Home Assistant to use this device as a Bluetooth proxy
# REQUIRES esp32_ble_tracker to be configured above
bluetooth_proxy:
  # Enable/disable the proxy
  # true = proxy active, false = proxy disabled
  active: false

  # Maximum number of simultaneous BLE connections
  # Default: 3, Range: 1-9
  # Higher values = more devices but more memory usage
  connection_slots: 1

# ESP32 Improv Configuration (Optional)
# Allows WiFi provisioning via BLE using the Improv standard
# Useful for initial device setup without hardcoded credentials
# esp32_improv:
#   # Authorization mode
#   # none = no authorization required (open provisioning)
#   # Use with caution - anyone can provision the device
#   authorizer: none

# API Integration - Dynamic BLE Scanning
# Automatically start/stop BLE scanning based on Home Assistant connection
# This saves power and reduces heap usage when HA is disconnected
api:
  on_client_connected:
    # Start BLE scanning when Home Assistant connects
    # Uses continuous mode for immediate device detection
    - delay: 500ms  # Brief delay to allow API to stabilize
    - esp32_ble_tracker.start_scan:
        continuous: true

  on_client_disconnected:
    # Stop BLE scanning when Home Assistant disconnects
    # Saves power and reduces heap pressure
    - esp32_ble_tracker.stop_scan:
