esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    # Always on
    #interval: 1100ms
    #window: 1100ms
    # More reasonable
    interval: 500ms
    window: 40ms
    # Defaults
    #interval: 320ms
    #window: 30ms
    active: true
    #active: false
    continuous: false