# ============================================================================
# LVGL Pages - WiFi Only Configuration (Config 3)
# ============================================================================
# This package defines LVGL pages for devices with WiFi monitoring only
#
# Includes:
#   - Vertical Clock page
#   - WiFi page (NO WireGuard)
#   - Page rotation handler (embedded, Clock + WiFi)
#
# Excludes:
#   - AirQ page (use airq-stubs)
#   - WireGuard status (use lvgl-pages-wifi-wireguard.yaml for WireGuard)
#   - Weather pages (use weather-stubs)
#   - BLE pages (use ble-stubs)
#
# Memory Impact: ~85KB total, ~125KB free
# BLE Compatible: YES (Config 3 + BLE)
#
# Usage: Config 3 - Clock + WiFi monitoring only
# ============================================================================

lvgl:
  pages:
    # Core pages - always available
    - !include vertical-clock-display.yaml

    # WiFi page (without WireGuard support)
    - !include lvgl-wifi-page.yaml

# ============================================================================
# PAGE ROTATION HANDLER - Embedded for Clock + WiFi configuration
# ============================================================================
# This handler supports: Clock and WiFi pages only (no AirQ, no Weather)

interval:
  - interval: 100ms  # Check frequently for page index changes
    then:
      - if:
          condition:
            lambda: |-
              static int last_displayed_index = -1;

              // Don't do anything until boot is complete
              if (!id(boot_complete)) return false;

              // Check if page index has changed
              int current = id(current_page_index);
              if (current == last_displayed_index) return false;

              // Page index changed
              last_displayed_index = current;
              ESP_LOGD("page_rotation", "Page index changed to %d", current);
              return true;
          then:
            # Page 0: Vertical Clock (always available)
            - if:
                condition:
                  lambda: 'return id(current_page_index) == 0;'
                then:
                  - logger.log: "Page rotation: Showing Vertical Clock (index 0)"
                  - lvgl.page.show:
                      id: vertical_clock_page
                      animation: OUT_LEFT
                      time: 300ms
                else:
                  # Page 2: WiFi (index 1 reserved for AirQ)
                  - if:
                      condition:
                        lambda: 'return id(current_page_index) == 2;'
                      then:
                        - logger.log: "Page rotation: Showing WiFi page (index 2)"
                        - lvgl.page.show:
                            id: wifi_page
                            animation: OUT_LEFT
                            time: 300ms
                      else:
                        # Unknown page - fall back to vertical clock
                        - logger.log:
                            format: "Page rotation: Page index %d not available, falling back to Vertical Clock"
                            args: ['id(current_page_index)']
                            level: WARN
                        - lvgl.page.show:
                            id: vertical_clock_page
                            animation: OUT_LEFT
                            time: 300ms

# ============================================================================
# NOTE: TIME UPDATE SCRIPT
# ============================================================================
# The time_update script is provided by the time-update-*.yaml package,
# NOT by this file. This file only defines LVGL pages and page rotation handler.
#
# The time-update package (time-update-wifi-only.yaml for this config) handles:
#   - Updating the vertical clock time display
#   - Time format switching (12h/24h)
#   - Clock colon blinking
#   - SNTP/HA time source selection (for WireGuard configs)
#
# Page rotation (auto page switching) is handled by the interval below.