# ============================================================================
# LVGL Pages - AirQ + Weather Forecast Only Configuration (Config 13a)
# ============================================================================
# This package defines LVGL pages for AirQ + minimal weather
#
# Includes:
#   - Vertical Clock page
#   - AirQ page
#   - Weather Forecast page (current conditions only)
#   - Page rotation handler (embedded, Clock + AirQ + Forecast)
#
# Excludes:
#   - WiFi page (use wifi-stubs)
#   - Daily forecast pages
#   - Hourly forecast pages
#
# Memory Impact: ~130KB total, ~80KB free
# BLE Compatible: NO (AirQ + Weather + BLE = ~190KB, too much)
#
# Usage: Config 13a - AirQ monitoring + minimal weather forecast
# Requires: weather-sensors-current.yaml (8 sensors only)
# ============================================================================

lvgl:
  pages:
    # Core pages - always available
    - !include vertical-clock-display.yaml

    # AirQ page
    - !include airq-display.yaml

    # Weather Forecast page (current conditions only)
    - !include weather-page-forecast.yaml

# ============================================================================
# PAGE ROTATION HANDLER - Embedded for Clock + AirQ + Weather Forecast
# ============================================================================
# This handler supports: Clock, AirQ, and Weather Forecast pages

interval:
  - interval: 100ms  # Check frequently for page index changes
    then:
      - if:
          condition:
            lambda: |-
              static int last_displayed_index = -1;

              // Don't do anything until boot is complete
              if (!id(boot_complete)) return false;

              // Check if page index has changed
              int current = id(current_page_index);
              if (current == last_displayed_index) return false;

              // Page index changed
              last_displayed_index = current;
              ESP_LOGD("page_rotation", "Page index changed to %d", current);
              return true;
          then:
            # Page 0: vertical_clock_page
            - if:
                condition:
                  lambda: 'return id(current_page_index) == 0;'
                then:
                  - logger.log: "Page rotation: Showing vertical_clock_page (index 0)"
                  - lvgl.page.show:
                      id: vertical_clock_page
                      animation: OUT_LEFT
                      time: 300ms
                else:
                  # Page 1: AirQ_page
                  - if:
                      condition:
                        lambda: 'return id(current_page_index) == 1;'
                      then:
                        - logger.log: "Page rotation: Showing AirQ_page (index 1)"
                        - lvgl.page.show:
                            id: AirQ_page
                            animation: OUT_LEFT
                            time: 300ms
                      else:
                  # Page 3: weather_forecast_page
                  - if:
                      condition:
                        lambda: 'return id(current_page_index) == 3;'
                      then:
                        - logger.log: "Page rotation: Showing weather_forecast_page (index 3)"
                        - lvgl.page.show:
                            id: weather_forecast_page
                            animation: OUT_LEFT
                            time: 300ms
                      else:
                        # Unknown page - fall back to vertical clock
                        - logger.log:
                            format: "Page rotation: Page index %d not available, falling back to Vertical Clock"
                            args: ['id(current_page_index)']
                            level: WARN
                        - lvgl.page.show:
                            id: vertical_clock_page
                            animation: OUT_LEFT
                            time: 300ms

# ============================================================================
# TIME UPDATE SCRIPT - Override Core's basic time update
# ============================================================================

script:
# ============================================================================
# NOTE: TIME UPDATE SCRIPT
# ============================================================================
# The time_update script is provided by the time-update-*.yaml package,
# NOT by this file. This file only defines LVGL pages and page rotation handler.
#
# The time-update package handles:
#   - Updating the vertical clock time display
#   - Time format switching (12h/24h)
#   - Clock colon blinking
#   - SNTP/HA time source selection (for WireGuard configs)
#
# Page rotation (auto page switching) is handled by the interval above.