# ============================================================================
# LVGL Pages - Full Configuration
# ============================================================================
# This package defines LVGL pages for devices with all features enabled
#
# Includes:
#   - Vertical Clock page
#   - AirQ page
#   - WiFi/WireGuard page
#   - Weather pages (forecast, hourly, daily, detailed day pages)
#   - Page rotation handler (embedded, full configuration)
#
# Usage: Include this for full-featured devices
# ============================================================================

lvgl:
  pages:
    # Core pages - always available
    - !include vertical-clock-display.yaml

    # AirQ page
    - !include airq-display.yaml

    # WiFi page (with WireGuard support)
    - !include lvgl-wifi-wireguard-page.yaml

    # Weather pages
    - !include weather-page-forecast.yaml       # Page 3: Current weather
    - !include weather-page-hourly.yaml         # Page 4: Hourly forecast
    - !include weather-page-hourly-2.yaml       # Page 4 alternate: Hourly forecast
    - !include weather-page-daily.yaml          # Page 5: Daily forecast overview
    - !include weather-page-days-4-5.yaml       # Days 4-5 detailed
    - !include weather-page-days-6-7.yaml       # Days 6-7 detailed
    - !include weather-page-days-8-9.yaml       # Days 8-9 detailed
    - !include weather-page-day-10.yaml         # Day 10 detailed

# ============================================================================
# PAGE ROTATION HANDLER - Embedded for full configuration
# ============================================================================
# This handler supports all page types: Clock, AirQ, WiFi, and Weather pages

interval:
  - interval: 100ms  # Check frequently for page index changes
    then:
      - if:
          condition:
            lambda: |-
              static int last_displayed_index = -1;

              // Don't do anything until boot is complete
              if (!id(boot_complete)) return false;

              // Check if page index has changed
              int current = id(current_page_index);
              if (current == last_displayed_index) return false;

              // Page index changed
              last_displayed_index = current;
              ESP_LOGD("page_rotation", "Page index changed to %d", current);
              return true;
          then:
            # Page 0: Vertical Clock
            - if:
                condition:
                  lambda: 'return id(current_page_index) == 0;'
                then:
                  - logger.log: "Page rotation: Showing Vertical Clock (index 0)"
                  - lvgl.page.show:
                      id: vertical_clock_page
                      animation: OUT_LEFT
                      time: 300ms
                else:
                  # Page 1: AirQ
                  - if:
                      condition:
                        lambda: 'return id(current_page_index) == 1;'
                      then:
                        - logger.log: "Page rotation: Showing AirQ page (index 1)"
                        - lvgl.page.show:
                            id: AirQ_page
                            animation: OUT_LEFT
                            time: 300ms
                      else:
                        # Page 2: WiFi
                        - if:
                            condition:
                              lambda: 'return id(current_page_index) == 2;'
                            then:
                              - logger.log: "Page rotation: Showing WiFi page (index 2)"
                              - lvgl.page.show:
                                  id: wifi_page
                                  animation: OUT_LEFT
                                  time: 300ms
                            else:
                              # Page 3: Weather
                              - if:
                                  condition:
                                    lambda: 'return id(current_page_index) == 3;'
                                  then:
                                    - logger.log: "Page rotation: Showing Weather page (index 3)"
                                    - lvgl.page.show:
                                        id: weather_forecast_page
                                        animation: OUT_LEFT
                                        time: 300ms
                                  else:
                                    # Page 4: Hourly Forecast
                                    - if:
                                        condition:
                                          lambda: 'return id(current_page_index) == 4;'
                                        then:
                                          - logger.log: "Page rotation: Showing Hourly Forecast page (index 4)"
                                          - lvgl.page.show:
                                              id: weather_hourly_forecast_page
                                              animation: OUT_LEFT
                                              time: 300ms
                                        else:
                                          # Page 5: Daily Forecast
                                          - if:
                                              condition:
                                                lambda: 'return id(current_page_index) == 5;'
                                              then:
                                                - logger.log: "Page rotation: Showing Daily Forecast page (index 5)"
                                                - lvgl.page.show:
                                                    id: weather_daily_forecast_page
                                                    animation: OUT_LEFT
                                                    time: 300ms
                                              else:
                                                # Unknown page - fall back to vertical clock
                                                - logger.log:
                                                    format: "Page rotation: Page index %d not available, falling back to Vertical Clock"
                                                    args: ['id(current_page_index)']
                                                    level: WARN
                                                - lvgl.page.show:
                                                    id: vertical_clock_page
                                                    animation: OUT_LEFT
                                                    time: 300ms
