# ============================================================================
# LVGL Pages - Weather Forecast + Hourly Configuration (Config 9)
# ============================================================================
# This package defines LVGL pages for devices with current + hourly forecasts
#
# Includes:
#   - Vertical Clock page
#   - Weather Forecast page (current conditions)
#   - Hourly Forecast pages (Hours 1-6, across 2 pages)
#   - Page rotation handler (embedded, Clock + Weather)
#
# Excludes:
#   - AirQ page (use airq-stubs)
#   - WiFi page (use wifi-stubs)
#   - Daily forecast pages
#
# Memory Impact: ~155KB total, ~55KB free
# BLE Compatible: NO (too much memory)
#
# Usage: Config 9 - Current + 6-hour detailed forecasts
# Requires:
#   - weather-sensors-current.yaml (8 sensors)
#   - weather-sensors-hourly.yaml (72 sensors)
# ============================================================================

lvgl:
  pages:
    # Core pages - always available
    - !include vertical-clock-display.yaml

    # Weather pages
    - !include weather-page-forecast.yaml      # Current forecast
    - !include weather-page-hourly.yaml        # Hours 1-3
    - !include weather-page-hourly-2.yaml      # Hours 4-6

# ============================================================================
# PAGE ROTATION HANDLER - Embedded for Clock + Weather Forecast + Hourly
# ============================================================================
# This handler supports: Clock, Forecast, and Hourly pages (3 weather pages total)

interval:
  - interval: 100ms  # Check frequently for page index changes
    then:
      - if:
          condition:
            lambda: |-
              static int last_displayed_index = -1;

              // Don't do anything until boot is complete
              if (!id(boot_complete)) return false;

              // Check if page index has changed
              int current = id(current_page_index);
              if (current == last_displayed_index) return false;

              // We have a page change - process it
              last_displayed_index = current;

              // Page mapping for Clock + Weather Forecast + Hourly:
              // 0 = Vertical Clock
              // 1 = Weather Forecast (current)
              // 2 = Hourly Forecast (Hours 1-3)
              // 3 = Hourly Forecast (Hours 4-6)

              switch(current) {
                case 0:
                  id(lily_display).show_page(vertical_clock_page);
                  ESP_LOGD("page_rotation", "Showing Vertical Clock page (index 0)");
                  break;
                case 1:
                  id(lily_display).show_page(weather_forecast_page);
                  ESP_LOGD("page_rotation", "Showing Weather Forecast page (index 1)");
                  break;
                case 2:
                  id(lily_display).show_page(hourly_forecast_page);
                  ESP_LOGD("page_rotation", "Showing Hourly Forecast Hours 1-3 (index 2)");
                  break;
                case 3:
                  id(lily_display).show_page(hourly_forecast_page_2);
                  ESP_LOGD("page_rotation", "Showing Hourly Forecast Hours 4-6 (index 3)");
                  break;
                default:
                  // Invalid page index - show clock
                  id(lily_display).show_page(vertical_clock_page);
                  ESP_LOGW("page_rotation", "Invalid page index %d, showing clock", current);
                  break;
              }

              return true;
          then:
            - logger.log:
                format: "Page displayed successfully"
                level: DEBUG

# ============================================================================
# TIME UPDATE SCRIPT - Override Core's basic time update
# ============================================================================
# Supports automatic page rotation through all weather pages

script:
# ============================================================================
# NOTE: TIME UPDATE SCRIPT
# ============================================================================
# The time_update script is provided by the time-update-*.yaml package,
# NOT by this file. This file only defines LVGL pages and page rotation handler.
#
# The time-update package handles:
#   - Updating the vertical clock time display
#   - Time format switching (12h/24h)
#   - Clock colon blinking
#   - SNTP/HA time source selection (for WireGuard configs)
#
# Page rotation (auto page switching) is handled by the interval above.