# ============================================================================
# LVGL Pages - AirQ + WiFi Configuration
# ============================================================================
# This package defines LVGL pages for devices with AirQ and WiFi monitoring
#
# Includes:
#   - Vertical Clock page
#   - AirQ page
#   - WiFi/WireGuard page
#   - Page rotation handler (embedded, AirQ + WiFi)
#
# Excludes:
#   - Weather pages (disabled via weather-stubs)
#   - BLE pages (disabled via ble-stubs)
#
# Usage: Include this for devices that monitor air quality and WiFi/VPN status
# ============================================================================

lvgl:
  pages:
    # Core pages - always available
    - !include vertical-clock-display.yaml

    # AirQ page - enabled
    - !include airq-display.yaml

    # WiFi page (with WireGuard support)
    - !include lvgl-wifi-wireguard-page.yaml

# ============================================================================
# PAGE ROTATION HANDLER - Embedded for AirQ + WiFi configuration
# ============================================================================
# This handler supports: Clock, AirQ, and WiFi pages (no Weather)

interval:
  - interval: 100ms  # Check frequently for page index changes
    then:
      - if:
          condition:
            lambda: |-
              static int last_displayed_index = -1;

              // Don't do anything until boot is complete
              if (!id(boot_complete)) return false;

              // Check if page index has changed
              int current = id(current_page_index);
              if (current == last_displayed_index) return false;

              // Page index changed
              last_displayed_index = current;
              ESP_LOGD("page_rotation", "Page index changed to %d", current);
              return true;
          then:
            # Page 0: Vertical Clock
            - if:
                condition:
                  lambda: 'return id(current_page_index) == 0;'
                then:
                  - logger.log: "Page rotation: Showing Vertical Clock (index 0)"
                  - lvgl.page.show:
                      id: vertical_clock_page
                      animation: OUT_LEFT
                      time: 300ms
                else:
                  # Page 1: AirQ
                  - if:
                      condition:
                        lambda: 'return id(current_page_index) == 1;'
                      then:
                        - logger.log: "Page rotation: Showing AirQ page (index 1)"
                        - lvgl.page.show:
                            id: AirQ_page
                            animation: OUT_LEFT
                            time: 300ms
                      else:
                        # Page 2: WiFi
                        - if:
                            condition:
                              lambda: 'return id(current_page_index) == 2;'
                            then:
                              - logger.log: "Page rotation: Showing WiFi page (index 2)"
                              - lvgl.page.show:
                                  id: wifi_page
                                  animation: OUT_LEFT
                                  time: 300ms
                            else:
                              # Unknown page - fall back to vertical clock
                              - logger.log:
                                  format: "Page rotation: Page index %d not available, falling back to Vertical Clock"
                                  args: ['id(current_page_index)']
                                  level: WARN
                              - lvgl.page.show:
                                  id: vertical_clock_page
                                  animation: OUT_LEFT
                                  time: 300ms
