# ============================================================================
# LVGL Pages - WiFi + Weather Forecast Only Configuration (Config 14a)
# ============================================================================
# This package defines LVGL pages for WiFi monitoring + minimal weather
#
# Includes:
#   - Vertical Clock page
#   - WiFi page (no WireGuard)
#   - Weather Forecast page (current conditions only)
#   - Page rotation handler (embedded, Clock + WiFi + Forecast)
#
# Excludes:
#   - AirQ page (use airq-stubs)
#   - WireGuard status (use wifi-weather-wireguard for WireGuard)
#   - Daily forecast pages
#   - Hourly forecast pages
#
# Memory Impact: ~135KB total, ~75KB free
# BLE Compatible: NO (WiFi + Weather + BLE = ~195KB, too much)
#
# Usage: Config 14a - WiFi monitoring + minimal weather forecast
# Requires: weather-sensors-current.yaml (8 sensors only)
# ============================================================================

lvgl:
  pages:
    # Core pages - always available
    - !include vertical-clock-display.yaml

    # WiFi page (without WireGuard)
    - !include lvgl-wifi-page.yaml

    # Weather Forecast page (current conditions only)
    - !include weather-page-forecast.yaml

# ============================================================================
# PAGE ROTATION HANDLER - Embedded for Clock + WiFi + Weather Forecast
# ============================================================================
# This handler supports: Clock, WiFi, and Weather Forecast pages

interval:
  - interval: 100ms  # Check frequently for page index changes
    then:
      - if:
          condition:
            lambda: |-
              static int last_displayed_index = -1;

              // Don't do anything until boot is complete
              if (!id(boot_complete)) return false;

              // Check if page index has changed
              int current = id(current_page_index);
              if (current == last_displayed_index) return false;

              // We have a page change - process it
              last_displayed_index = current;

              // Page mapping for Clock + WiFi + Weather Forecast:
              // 0 = Vertical Clock
              // 1 = WiFi
              // 2 = Weather Forecast

              switch(current) {
                case 0:
                  id(lily_display).show_page(vertical_clock_page);
                  ESP_LOGD("page_rotation", "Showing Vertical Clock page (index 0)");
                  break;
                case 1:
                  id(lily_display).show_page(wifi_page);
                  ESP_LOGD("page_rotation", "Showing WiFi page (index 1)");
                  break;
                case 2:
                  id(lily_display).show_page(weather_forecast_page);
                  ESP_LOGD("page_rotation", "Showing Weather Forecast page (index 2)");
                  break;
                default:
                  // Invalid page index - show clock
                  id(lily_display).show_page(vertical_clock_page);
                  ESP_LOGW("page_rotation", "Invalid page index %d, showing clock", current);
                  break;
              }

              return true;
          then:
            - logger.log:
                format: "Page displayed successfully"
                level: DEBUG

# ============================================================================
# TIME UPDATE SCRIPT - Override Core's basic time update
# ============================================================================

script:
# ============================================================================
# NOTE: TIME UPDATE SCRIPT
# ============================================================================
# The time_update script is provided by the time-update-*.yaml package,
# NOT by this file. This file only defines LVGL pages and page rotation handler.
#
# The time-update package handles:
#   - Updating the vertical clock time display
#   - Time format switching (12h/24h)
#   - Clock colon blinking
#   - SNTP/HA time source selection (for WireGuard configs)
#
# Page rotation (auto page switching) is handled by the interval above.