# ============================================================================
# LVGL Pages - Weather Forecast Only Configuration (Config 7)
# ============================================================================
# This package defines LVGL pages for devices with MINIMAL weather
#
# Includes:
#   - Vertical Clock page
#   - Weather Forecast page (current conditions only)
#   - Page rotation handler (embedded, Clock + Forecast)
#
# Excludes:
#   - AirQ page (use airq-stubs)
#   - WiFi page (use wifi-stubs)
#   - Daily forecast pages
#   - Hourly forecast pages
#
# Memory Impact: ~110KB total, ~100KB free
# BLE Compatible: YES! (Config 7 + BLE = ~170KB, ~40KB free - tight but works)
#
# Usage: Config 7 - Minimal weather for BLE coexistence
# Requires: weather-sensors-current.yaml (8 sensors only)
#
# This is the ONLY weather configuration compatible with BLE!
# ============================================================================

lvgl:
  pages:
    # Core pages - always available
    - !include vertical-clock-display.yaml

    # Weather Forecast page (current conditions only)
    - !include weather-page-forecast.yaml

# ============================================================================
# PAGE ROTATION HANDLER - Embedded for Clock + Weather Forecast configuration
# ============================================================================
# This handler supports: Clock and Weather Forecast pages only

interval:
  - interval: 100ms  # Check frequently for page index changes
    then:
      - if:
          condition:
            lambda: |-
              static int last_displayed_index = -1;

              // Don't do anything until boot is complete
              if (!id(boot_complete)) return false;

              // Check if page index has changed
              int current = id(current_page_index);
              if (current == last_displayed_index) return false;

              // We have a page change - process it
              last_displayed_index = current;

              // Page mapping for Clock + Weather Forecast:
              // 0 = Vertical Clock
              // 1 = Weather Forecast

              switch(current) {
                case 0:
                  id(lily_display).show_page(vertical_clock_page);
                  ESP_LOGD("page_rotation", "Showing Vertical Clock page (index 0)");
                  break;
                case 1:
                  id(lily_display).show_page(weather_forecast_page);
                  ESP_LOGD("page_rotation", "Showing Weather Forecast page (index 1)");
                  break;
                default:
                  // Invalid page index - show clock
                  id(lily_display).show_page(vertical_clock_page);
                  ESP_LOGW("page_rotation", "Invalid page index %d, showing clock", current);
                  break;
              }

              return true;
          then:
            - logger.log:
                format: "Page displayed successfully"
                level: DEBUG

# ============================================================================
# TIME UPDATE SCRIPT - Override Core's basic time update
# ============================================================================
# This script runs every second to update the current page index
# Supports automatic page rotation if enabled

script:
# ============================================================================
# NOTE: TIME UPDATE SCRIPT
# ============================================================================
# The time_update script is provided by the time-update-*.yaml package,
# NOT by this file. This file only defines LVGL pages and page rotation handler.
#
# The time-update package handles:
#   - Updating the vertical clock time display
#   - Time format switching (12h/24h)
#   - Clock colon blinking
#   - SNTP/HA time source selection (for WireGuard configs)
#
# Page rotation (auto page switching) is handled by the interval above.