# ============================================================================
# LVGL Pages - Clock Only Configuration
# ============================================================================
# This package defines LVGL pages for minimal devices with only clock display
#
# Includes:
#   - Vertical Clock page only
#   - Page rotation handler (embedded, clock-only)
#
# Excludes:
#   - AirQ pages (disabled via airq-stubs)
#   - WiFi pages (disabled via wifi-stubs)
#   - Weather pages (disabled via weather-stubs)
#   - BLE pages (disabled via ble-stubs)
#
# Usage: Include this for minimal clock-only devices
# ============================================================================

lvgl:
  pages:
    # Core pages - clock only
    - !include vertical-clock-display.yaml

# ============================================================================
# PAGE ROTATION HANDLER - Embedded for clock-only configuration
# ============================================================================
# This handler is specific to this page configuration and only references
# the Vertical Clock page (since that's all that exists).

interval:
  - interval: 100ms  # Check frequently for page index changes
    then:
      - if:
          condition:
            lambda: |-
              static int last_displayed_index = -1;

              // Don't do anything until boot is complete
              if (!id(boot_complete)) return false;

              // Check if page index has changed
              int current = id(current_page_index);
              if (current == last_displayed_index) return false;

              // Page index changed
              last_displayed_index = current;
              ESP_LOGD("page_rotation", "Page index changed to %d", current);
              return true;
          then:
            # Only vertical clock exists - always show it
            - logger.log: "Page rotation: Showing Vertical Clock (only page available)"
            - lvgl.page.show:
                id: vertical_clock_page
                animation: OUT_LEFT
                time: 300ms
