# ============================================================================
# LVGL Pages - AirQ + Weather Configuration
# ============================================================================
# This package defines LVGL pages for devices with AirQ and Weather enabled
#
# Includes:
#   - Vertical Clock page
#   - AirQ page
#   - Weather pages (forecast, hourly, daily, detailed day pages)
#
# Excludes:
#   - WiFi pages (disabled via wifi-stubs)
#   - BLE pages (disabled via ble-stubs)
#
# Usage: Include this for devices that monitor both air quality and weather
# ============================================================================

# Define which pages exist in this configuration
# These flags are used by page-rotation-handler.yaml to know which pages to show
substitutions:
  page_exists_vertical_clock: "true"
  page_exists_airq: "true"
  page_exists_wifi: "false"
  page_exists_weather: "true"
  page_exists_hourly_forecast: "true"
  page_exists_daily_forecast: "true"

lvgl:
  pages:
    # Core pages - always available
    - !include vertical-clock-display.yaml

    # AirQ page - enabled
    - !include airq-display.yaml

    # Weather pages - enabled
    - !include weather-page-forecast.yaml       # Page 3: Current weather
    - !include weather-page-hourly.yaml         # Page 4: Hourly forecast
    - !include weather-page-hourly-2.yaml       # Page 4 alternate: Hourly forecast
    - !include weather-page-daily.yaml          # Page 5: Daily forecast overview
    - !include weather-page-days-4-5.yaml       # Days 4-5 detailed
    - !include weather-page-days-6-7.yaml       # Days 6-7 detailed
    - !include weather-page-days-8-9.yaml       # Days 8-9 detailed
    - !include weather-page-day-10.yaml         # Day 10 detailed
