# ============================================================================
# LVGL Pages - AirQ + Weather Forecast Only Configuration (Config 13a)
# ============================================================================
# This package defines LVGL pages for AirQ + minimal weather
#
# Includes:
#   - Vertical Clock page
#   - AirQ page
#   - Weather Forecast page (current conditions only)
#   - Page rotation handler (embedded, Clock + AirQ + Forecast)
#
# Excludes:
#   - WiFi page (use wifi-stubs)
#   - Daily forecast pages
#   - Hourly forecast pages
#
# Memory Impact: ~130KB total, ~80KB free
# BLE Compatible: NO (AirQ + Weather + BLE = ~190KB, too much)
#
# Usage: Config 13a - AirQ monitoring + minimal weather forecast
# Requires: weather-sensors-current.yaml (8 sensors only)
# ============================================================================

lvgl:
  pages:
    # Core pages - always available
    - !include vertical-clock-display.yaml

    # AirQ page
    - !include airq-display.yaml

    # Weather Forecast page (current conditions only)
    - !include weather-page-forecast.yaml

# ============================================================================
# PAGE ROTATION HANDLER - Embedded for Clock + AirQ + Weather Forecast
# ============================================================================
# This handler supports: Clock, AirQ, and Weather Forecast pages

interval:
  - interval: 100ms  # Check frequently for page index changes
    then:
      - if:
          condition:
            lambda: |-
              static int last_displayed_index = -1;

              // Don't do anything until boot is complete
              if (!id(boot_complete)) return false;

              // Check if page index has changed
              int current = id(current_page_index);
              if (current == last_displayed_index) return false;

              // We have a page change - process it
              last_displayed_index = current;

              // Page mapping for Clock + AirQ + Weather Forecast:
              // 0 = Vertical Clock
              // 1 = AirQ
              // 2 = Weather Forecast

              switch(current) {
                case 0:
                  id(lily_display).show_page(vertical_clock_page);
                  ESP_LOGD("page_rotation", "Showing Vertical Clock page (index 0)");
                  break;
                case 1:
                  id(lily_display).show_page(AirQ_page);
                  ESP_LOGD("page_rotation", "Showing AirQ page (index 1)");
                  break;
                case 2:
                  id(lily_display).show_page(weather_forecast_page);
                  ESP_LOGD("page_rotation", "Showing Weather Forecast page (index 2)");
                  break;
                default:
                  // Invalid page index - show clock
                  id(lily_display).show_page(vertical_clock_page);
                  ESP_LOGW("page_rotation", "Invalid page index %d, showing clock", current);
                  break;
              }

              return true;
          then:
            - logger.log:
                format: "Page displayed successfully"
                level: DEBUG

# ============================================================================
# TIME UPDATE SCRIPT - Override Core's basic time update
# ============================================================================

script:
  - id: time_update
    mode: restart
    then:
      - lambda: |-
          // Get current time
          auto time = id(halo_time).now();

          // Handle automatic page rotation
          if (id(page_rotation_enabled)) {
            uint32_t now = millis();
            uint32_t elapsed = now - id(last_auto_rotation_time);
            uint32_t rotation_interval = id(page_rotation_interval) * 1000;

            if (elapsed >= rotation_interval) {
              id(last_auto_rotation_time) = now;

              // Build list of enabled pages
              std::vector<int> enabled_pages;

              // Clock is always available
              enabled_pages.push_back(0);

              // AirQ page (if enabled)
              if (id(page_rotation_airq_enabled)) {
                enabled_pages.push_back(1);
              }

              // Weather Forecast page (if enabled)
              if (id(page_rotation_weather_enabled)) {
                enabled_pages.push_back(2);
              }

              // Find current page and rotate to next
              int current_idx = id(current_page_index);
              int current_pos = -1;
              for (size_t i = 0; i < enabled_pages.size(); i++) {
                if (enabled_pages[i] == current_idx) {
                  current_pos = i;
                  break;
                }
              }

              if (current_pos >= 0 && enabled_pages.size() > 1) {
                int next_pos = (current_pos + 1) % enabled_pages.size();
                id(current_page_index) = enabled_pages[next_pos];
                ESP_LOGD("page_rotation", "Auto-rotating to page %d", id(current_page_index));
              }
            }
          }
