# ============================================================================
# LVGL Pages - Weather Forecast + Daily Configuration (Config 8)
# ============================================================================
# This package defines LVGL pages for devices with current + daily forecasts
#
# Includes:
#   - Vertical Clock page
#   - Weather Forecast page (current conditions)
#   - Daily Forecast pages (Days 2-10, across 5 pages)
#   - Page rotation handler (embedded, Clock + Weather)
#
# Excludes:
#   - AirQ page (use airq-stubs)
#   - WiFi page (use wifi-stubs)
#   - Hourly forecast pages
#
# Memory Impact: ~165KB total, ~45KB free
# BLE Compatible: NO (too much memory)
#
# Usage: Config 8 - Full daily forecasts without hourly
# Requires:
#   - weather-sensors-current.yaml (8 sensors)
#   - weather-sensors-daily.yaml (45 sensors)
# ============================================================================

lvgl:
  pages:
    # Core pages - always available
    - !include vertical-clock-display.yaml

    # Weather pages
    - !include weather-page-forecast.yaml      # Current forecast
    - !include weather-page-daily.yaml         # Days 2-3
    - !include weather-page-days-4-5.yaml      # Days 4-5
    - !include weather-page-days-6-7.yaml      # Days 6-7
    - !include weather-page-days-8-9.yaml      # Days 8-9
    - !include weather-page-day-10.yaml        # Day 10

# ============================================================================
# PAGE ROTATION HANDLER - Embedded for Clock + Weather Forecast + Daily
# ============================================================================
# This handler supports: Clock, Forecast, and Daily pages (6 weather pages total)

interval:
  - interval: 100ms  # Check frequently for page index changes
    then:
      - if:
          condition:
            lambda: |-
              static int last_displayed_index = -1;

              // Don't do anything until boot is complete
              if (!id(boot_complete)) return false;

              // Check if page index has changed
              int current = id(current_page_index);
              if (current == last_displayed_index) return false;

              // Page index changed
              last_displayed_index = current;
              ESP_LOGD("page_rotation", "Page index changed to %d", current);
              return true;
          then:
            # Page 0: vertical_clock_page
            - if:
                condition:
                  lambda: 'return id(current_page_index) == 0;'
                then:
                  - logger.log: "Page rotation: Showing vertical_clock_page (index 0)"
                  - lvgl.page.show:
                      id: vertical_clock_page
                      animation: OUT_LEFT
                      time: 300ms
                else:
                  # Page 3: weather_forecast_page
                  - if:
                      condition:
                        lambda: 'return id(current_page_index) == 3;'
                      then:
                        - logger.log: "Page rotation: Showing weather_forecast_page (index 3)"
                        - lvgl.page.show:
                            id: weather_forecast_page
                            animation: OUT_LEFT
                            time: 300ms
                      else:
                        # Unknown page - fall back to vertical clock
                        - logger.log:
                            format: "Page rotation: Page index %d not available, falling back to Vertical Clock"
                            args: ['id(current_page_index)']
                            level: WARN
                        - lvgl.page.show:
                            id: vertical_clock_page
                            animation: OUT_LEFT
                            time: 300ms

# ============================================================================
# TIME UPDATE SCRIPT - Override Core's basic time update
# ============================================================================
# Supports automatic page rotation through all weather pages

script:
# ============================================================================
# NOTE: TIME UPDATE SCRIPT
# ============================================================================
# The time_update script is provided by the time-update-*.yaml package,
# NOT by this file. This file only defines LVGL pages and page rotation handler.
#
# The time-update package handles:
#   - Updating the vertical clock time display
#   - Time format switching (12h/24h)
#   - Clock colon blinking
#   - SNTP/HA time source selection (for WireGuard configs)
#
# Page rotation (auto page switching) is handled by the interval above.