# LVGL WiFi Page Package (WiFi-only, no WireGuard)
# This package provides the LVGL WiFi status page WITHOUT WireGuard information
#
# Usage in your LVGL display configuration:
#   display:
#     - platform: ...
#       pages:
#         - !include packages/lvgl-wifi-page.yaml
#
# This package provides:
#   - WiFi statistics page with SSID, signal strength, and IP address
#   - WiFi signal strength bar with gradient
#   - Navigation button for page transitions
#
# Dependencies:
#   - Requires wifi-display.yaml package for the update logic
#   - Requires LVGL display configuration in main config
#   - Requires colors: my_white, my_gray
#   - Requires fonts: montserrat_18, montserrat_20
#   - Requires script: page_transition_cleanup
#   - Requires global: current_page_index, last_auto_rotation_time

# WiFi signal gradient (used by signal bar)
gradients:
  - id: wifi_signal_gradient
    direction: hor
    dither: none
    stops:
      - color: 0xFF0000  # Red - weak signal
        position: 0
      - color: 0xFF8000  # Orange
        position: 64
      - color: 0xFFFF00  # Yellow
        position: 128
      - color: 0x80FF00  # Yellow-green
        position: 192
      - color: 0x00FF00  # Green - strong signal
        position: 255

# WiFi Page (WiFi-only version without WireGuard)
pages:
  - id: wifi_page
  bg_color: 0x000000
  bg_opa: COVER
  scrollbar_mode: "OFF"
  on_load:
    - script.execute: page_transition_cleanup
    - lambda: 'id(current_page_index) = 2;'  # wifi_page
  widgets:
    - label:
        text: "WiFi Statistics"
        align: CENTER
        x: 0
        y: -250
        text_font: montserrat_20
        text_color: my_white
        text_align: CENTER
    - label:
        id: wifi_ssid_label
        text: "SSID: ...\n"
        align: LEFT_MID
        x: 10
        y: -180
        text_font: montserrat_18
        text_color: my_white
    - label:
        id: wifi_signal_label
        text: "Signal: ..."
        align: LEFT_MID
        x: 10
        y: -150
        text_font: montserrat_18
        text_color: my_white
    - bar:
        id: wifi_signal_bar
        align: CENTER
        x: 0
        y: -110
        width: 160
        height: 10
        min_value: -100
        max_value: -30
        value: -100
        bg_color: my_gray
        indicator:
          bg_grad: wifi_signal_gradient

    - label:
        id: wifi_ip_label
        text: "IP: ..."
        align: LEFT_MID
        x: 10
        y: -70
        text_font: montserrat_18
        text_color: my_white
    - obj:
        id: nav_button_wifi
        align: TOP_RIGHT
        x: 0
        y: 0
        width: 100
        height: 100
        bg_opa: 0
        border_width: 0
        clickable: true
        on_press:
          - logger.log: "WiFi page nav button PRESSED!"
          - lambda: |-
              ESP_LOGI("touch", "Navigation button touched");
              id(last_auto_rotation_time) = millis();
              ESP_LOGD("touch", "Auto-rotation timer reset");
          - lvgl.page.next:
              animation: OUT_LEFT
              time: 300ms
