# Page Registry Package
# Provides page name tracking for LVGL displays
#
# This package allows pages to identify themselves by name instead of only using
# hardcoded indices, making the configuration more modular.
#
# Usage:
#   packages:
#     page_registry: !include packages/page-registry.yaml
#
# How pages set their name:
#   In page's on_load:
#     - lambda: 'id(current_page_name) = "wifi"; id(current_page_index) = 2;'
#
# How to check current page in display packages:
#   Instead of: id(current_page_index) == 2
#   Use: id(current_page_name) == "wifi"
#
# Standard page names:
#   - "vertical_clock" - Vertical clock page
#   - "airq" - Air quality page
#   - "wifi" - WiFi/WireGuard status page
#   - "weather" - Weather forecast page (optional, from weather package)
#   - "hourly_forecast" - Hourly forecast page (optional, from weather package)
#   - "daily_forecast" - Daily forecast page (optional, from weather package)

globals:
  # Current page tracking using string name
  - id: current_page_name
    type: std::string
    restore_value: no
    initial_value: '"vertical_clock"'
