# ============================================================================
# Page Rotation Handler Package
# ============================================================================
# This package provides dynamic page rotation display handling that adapts
# to whatever pages are included in the LVGL pages configuration.
#
# Purpose:
#   - Core (Halo-v1-Core.yaml) calculates WHICH page to show (sets current_page_index)
#   - This handler watches current_page_index and DISPLAYS the appropriate page
#   - Works with any combination of enabled/disabled modules
#
# How it works:
#   1. Each LVGL pages package defines boolean flags for which pages exist
#   2. This handler uses cascading if-then-else to check each page
#   3. When current_page_index changes, shows the appropriate page (if it exists)
#   4. Falls back to vertical_clock_page if index not found
#
# Usage in device files:
#   packages:
#     page_rotation_handler:
#       url: https://github.com/truffshuff/halo/
#       ref: main
#       files: [TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/packages/page-rotation-handler.yaml]
#       refresh: always
#
# LVGL pages packages must define page existence flags (see lvgl-pages-*.yaml)
# ============================================================================

# Default page existence flags (will be overridden by LVGL pages packages)
# These ensure the handler doesn't fail if a package forgets to define them
substitutions:
  page_exists_vertical_clock: "true"   # Clock always exists
  page_exists_airq: "false"
  page_exists_wifi: "false"
  page_exists_weather: "false"
  page_exists_hourly_forecast: "false"
  page_exists_daily_forecast: "false"

# Interval that watches for page index changes and displays appropriate pages
interval:
  - interval: 100ms  # Check frequently for page index changes
    then:
      - if:
          condition:
            lambda: |-
              static int last_displayed_index = -1;

              // Don't do anything until boot is complete
              if (!id(boot_complete)) return false;

              // Check if page index has changed
              int current = id(current_page_index);
              if (current == last_displayed_index) return false;

              // Page index changed
              last_displayed_index = current;
              ESP_LOGD("page_rotation", "Page index changed to %d", current);
              return true;
          then:
            # Page 0: Vertical Clock (always available)
            - if:
                condition:
                  lambda: 'return id(current_page_index) == 0;'
                then:
                  - logger.log: "Page rotation: Showing Vertical Clock (index 0)"
                  - lvgl.page.show:
                      id: vertical_clock_page
                      animation: OUT_LEFT
                      time: 300ms
                else:
                  # Page 1: AirQ (only if enabled)
                  - if:
                      condition:
                        lambda: 'return id(current_page_index) == 1 && ${page_exists_airq};'
                      then:
                        - logger.log: "Page rotation: Showing AirQ page (index 1)"
                        - lvgl.page.show:
                            id: AirQ_page
                            animation: OUT_LEFT
                            time: 300ms
                      else:
                        # Page 2: WiFi (only if enabled)
                        - if:
                            condition:
                              lambda: 'return id(current_page_index) == 2 && ${page_exists_wifi};'
                            then:
                              - logger.log: "Page rotation: Showing WiFi page (index 2)"
                              - lvgl.page.show:
                                  id: wifi_page
                                  animation: OUT_LEFT
                                  time: 300ms
                            else:
                              # Page 3: Weather (only if enabled)
                              - if:
                                  condition:
                                    lambda: 'return id(current_page_index) == 3 && ${page_exists_weather};'
                                  then:
                                    - logger.log: "Page rotation: Showing Weather page (index 3)"
                                    - lvgl.page.show:
                                        id: weather_forecast_page
                                        animation: OUT_LEFT
                                        time: 300ms
                                  else:
                                    # Page 4: Hourly Forecast (only if enabled)
                                    - if:
                                        condition:
                                          lambda: 'return id(current_page_index) == 4 && ${page_exists_hourly_forecast};'
                                        then:
                                          - logger.log: "Page rotation: Showing Hourly Forecast page (index 4)"
                                          - lvgl.page.show:
                                              id: weather_hourly_forecast_page
                                              animation: OUT_LEFT
                                              time: 300ms
                                        else:
                                          # Page 5: Daily Forecast (only if enabled)
                                          - if:
                                              condition:
                                                lambda: 'return id(current_page_index) == 5 && ${page_exists_daily_forecast};'
                                              then:
                                                - logger.log: "Page rotation: Showing Daily Forecast page (index 5)"
                                                - lvgl.page.show:
                                                    id: weather_daily_forecast_page
                                                    animation: OUT_LEFT
                                                    time: 300ms
                                              else:
                                                # Unknown page or page not available - fall back to vertical clock
                                                - logger.log:
                                                    format: "Page rotation: Page index %d not available, falling back to Vertical Clock"
                                                    args: ['id(current_page_index)']
                                                    level: WARN
                                                - lvgl.page.show:
                                                    id: vertical_clock_page
                                                    animation: OUT_LEFT
                                                    time: 300ms
