################################################################################
# VERTICAL CLOCK - Display Page
# Description: LVGL page layout for vertical clock display
# Provides: vertical_clock_page LVGL page with time/date widgets
# Dependencies: vertical-clock-core.yaml (fonts, scripts)
# Mode: Default (always enabled)
################################################################################

id: vertical_clock_page
bg_color: 0x000000
bg_opa: COVER
scrollbar_mode: "OFF"
on_load:
  - script.execute: page_transition_cleanup
  - lambda: |-
      id(current_page_index) = 0;
      id(time_update_last_text).clear();
      id(colon_blink_state) = true;  // Ensure colon is visible when page loads
  - script.execute: time_update
  - script.execute: update_colon_widget
widgets:
  # Large time display vertically centered
  - label:
      id: vclock_hours
      align: CENTER
      text_font: montserrat_80
      text_color: my_white
      x: 0
      y: -120
      text: "12"

  - label:
      id: vclock_colon
      align: CENTER
      text_font: montserrat_80
      text_color: my_white
      x: 0
      y: -20
      text: ":"

  - label:
      id: vclock_minutes
      align: CENTER
      text_font: montserrat_80
      text_color: my_white
      x: 0
      y: 80
      text: "00"

  - label:
      id: vclock_ampm
      align: CENTER
      text_font: montserrat_50
      text_color: my_white
      x: 0
      y: 180
      text: "AM"

  # Date below time
  - label:
      id: vclock_date
      align: CENTER
      text_font: montserrat_24
      text_color: my_gray
      x: 0
      y: 250
      text: "Mon, Jan 1"

  # Day of week at top
  - label:
      id: vclock_day_top
      align: TOP_MID
      text_font: montserrat_24
      text_color: my_gray
      x: 0
      y: 20
      text: "Monday"

  # Navigation button (top right corner)
  - obj:
      id: nav_button_vclock
      align: TOP_RIGHT
      x: 0
      y: 0
      width: 100
      height: 100
      bg_opa: 0
      border_width: 0
      clickable: true
      on_press:
        - logger.log: "Vertical Clock page nav button PRESSED!"
        - lambda: |-
            ESP_LOGI("touch", "Navigation button touched");
            id(last_auto_rotation_time) = millis();
            ESP_LOGD("touch", "Auto-rotation timer reset");
        - lvgl.page.next:
            animation: OUT_LEFT
            time: 300ms
