id: forecast_day_10_page
  bg_color: 0x000000
bg_opa: COVER
scrollbar_mode: "OFF"
skip: true
on_load:
  - script.execute: page_transition_cleanup
widgets:
  - label:
      text: "Extended Forecast"
      align: TOP_MID
      y: 5
      text_font: montserrat_18
      text_color: my_white
      text_align: CENTER

  # Day 10 Card (centered on page)
  - obj:
      width: 170
      height: SIZE_CONTENT
      align: CENTER
      y: 0
      bg_color: 0x101010
      bg_opa: COVER
      border_width: 0
      radius: 12
      pad_all: 12
      scrollbar_mode: "OFF"
      layout:
        type: flex
        flex_flow: column
        pad_row: 6
      widgets:
        - label:
            id: lbl_forecast_day10_header
            text: "Day +10 (--/--)"
            text_font: montserrat_18
            text_color: my_white
        - label:
            id: lbl_forecast_day10_icon
            text: "--"
            text_font: icons_80
            text_color: my_white
        - label:
            id: lbl_forecast_day10_condition
            text: "---"
            text_font: montserrat_18
            text_color: my_white
            long_mode: SCROLL_CIRCULAR
        - label:
            id: lbl_forecast_day10_temps
            text: "H:--° L:--°"
            text_font: montserrat_18
            text_color: my_white
        - label:
            id: lbl_forecast_day10_precip_prob
            text: "Rain: --%"
            text_font: montserrat_16
            text_color: my_white

  # Navigation button (center bottom) - goes back to Days 2-3
  - obj:
      id: nav_button_forecast_10
      align: BOTTOM_MID
      x: 0
      y: 0
      width: 100
      height: 100
      bg_opa: 0
      border_width: 0
      clickable: true
      on_press:
        - logger.log: "Day 10 BOTTOM button PRESSED - going back to 3-day!"
        - lvgl.page.show:
            id: daily_forecast_page
            animation: OUT_RIGHT
            time: 300ms

  # Top-right button for main page navigation
  - obj:
      id: nav_button_top_10
      align: TOP_RIGHT
      x: 0
      y: 0
      width: 100
      height: 100
      bg_opa: 0
      border_width: 0
      clickable: true
      on_press:
        - logger.log: "Day 10 top-right button PRESSED!"
        - lvgl.page.next:
            animation: OUT_LEFT
            time: 300ms

# ===================================================================
