id: forecast_days_8_9_page
  bg_color: 0x000000
bg_opa: COVER
scrollbar_mode: "OFF"
skip: true
on_load:
  - script.execute: page_transition_cleanup
widgets:
  - label:
      text: "Extended Forecast"
      align: TOP_MID
      y: 5
      text_font: montserrat_18
      text_color: my_white
      text_align: CENTER

  # Day 8 Card
  - obj:
      width: 170
      height: SIZE_CONTENT
      align: TOP_MID
      y: 40
      bg_color: 0x101010
      bg_opa: COVER
      border_width: 0
      radius: 12
      pad_all: 12
      scrollbar_mode: "OFF"
      layout:
        type: flex
        flex_flow: column
        pad_row: 6
      widgets:
        - label:
            id: lbl_forecast_day8_header
            text: "Day +8 (--/--)"
            text_font: montserrat_18
            text_color: my_white
        - label:
            id: lbl_forecast_day8_icon
            text: "--"
            text_font: icons_80
            text_color: my_white
        - label:
            id: lbl_forecast_day8_condition
            text: "---"
            text_font: montserrat_18
            text_color: my_white
            long_mode: SCROLL_CIRCULAR
        - label:
            id: lbl_forecast_day8_temps
            text: "H:--째 L:--째"
            text_font: montserrat_18
            text_color: my_white
        - label:
            id: lbl_forecast_day8_precip_prob
            text: "Rain: --%"
            text_font: montserrat_16
            text_color: my_white

  # Day 9 Card
  - obj:
      width: 170
      height: SIZE_CONTENT
      align: TOP_MID
      y: 340
      bg_color: 0x101010
      bg_opa: COVER
      border_width: 0
      radius: 12
      pad_all: 12
      scrollbar_mode: "OFF"
      layout:
        type: flex
        flex_flow: column
        pad_row: 6
      widgets:
        - label:
            id: lbl_forecast_day9_header
            text: "Day +9 (--/--)"
            text_font: montserrat_18
            text_color: my_white
        - label:
            id: lbl_forecast_day9_icon
            text: "--"
            text_font: icons_80
            text_color: my_white
        - label:
            id: lbl_forecast_day9_condition
            text: "---"
            text_font: montserrat_18
            text_color: my_white
            long_mode: SCROLL_CIRCULAR
        - label:
            id: lbl_forecast_day9_temps
            text: "H:--째 L:--째"
            text_font: montserrat_18
            text_color: my_white
        - label:
            id: lbl_forecast_day9_precip_prob
            text: "Rain: --%"
            text_font: montserrat_16
            text_color: my_white

  # Top-right button for main page navigation
  - obj:
      id: nav_button_top_89
      align: TOP_RIGHT
      x: 0
      y: 0
      width: 100
      height: 100
      bg_opa: 0
      border_width: 0
      clickable: true
      on_press:
        - logger.log: "Days 8-9 top-right button PRESSED!"
        - lvgl.page.next:
            animation: OUT_LEFT
            time: 300ms

  - label:
      text: "More >"
      align: BOTTOM_MID
      y: -5
      text_font: montserrat_18
      text_color: my_gray
      text_align: CENTER

  # # Navigation button (center of screen) - must be LAST to render on top
  # - obj:
  #     id: nav_button_forecast_89
  #     align: CENTER
  #     x: 0
  #     y: 0
  #     width: 150
  #     height: 150
  #     bg_opa: 0
  #     border_width: 0
  #     clickable: true
  #     on_press:
  #       - logger.log: "Days 8-9 CENTER button PRESSED - going to Day 10!"
  #       - lvgl.page.show:
  #           id: forecast_day_10_page
  #           animation: OUT_LEFT
  #           time: 300ms

   # Navigation button (bottom of screen) - must be LAST to render on top
  - obj:
      id: nav_button_extended_forecast_89
      align: BOTTOM_MID
      x: 0
      y: 0
      width: 100
      height: 60
      bg_opa: 0
      border_width: 0
      clickable: true
      on_press:
        - logger.log: "Extended forecast 'More' button on 8-9 PRESSED! going to 10!"
        - lambda: |-
            ESP_LOGI("touch", "Navigation button touched");
            id(last_auto_rotation_time) = millis();
            ESP_LOGD("touch", "Auto-rotation timer reset");
        - lvgl.page.show:
            id: forecast_day_10_page
            animation: OUT_LEFT
            time: 300ms

