# Weather Feature Disabled
# This wrapper is included when weather_enabled: "false" in device config
# It provides stubs to prevent compilation errors while disabling weather

weather_disabled_wrapper: !include weather-stubs.yaml
