# Weather Fonts and Text Sensors Package
# Provides Material Design Icon fonts and LVGL text sensors for weather displays
#
# Usage:
#   packages:
#     weather_fonts_text: !include packages/weather-fonts-text.yaml
#
# This package provides:
#   - 5 weather icon fonts at different sizes (20px, 40px, 50px, 80px, 100px)
#   - 47 LVGL text sensors for updating weather widget text
#
# Dependencies:
#   - Requires weather-pages package for LVGL widgets
#   - Requires fonts/materialdesignicons-webfont.ttf file

# ===================================================================
# WEATHER ICON FONTS
# ===================================================================
# Material Design Icons fonts at various sizes for weather condition icons

font:
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_100
    size: 100
    bpp: 4
    glyphs: [
      "\U000F0594", # clear-night
      "\U000F0590", # cloudy
      "\U000F0F2F", # exceptional
      "\U000F0591", # fog
      "\U000F0592", # hail
      "\U000F0593", # lightning
      "\U000F067E", # lightning-rainy
      "\U000F0595", # partlycloudy
      "\U000F0596", # pouring
      "\U000F0597", # rainy
      "\U000F0598", # snowy
      "\U000F067F", # snowy-rainy
      "\U000F0599", # sunny
      "\U000F059D", # windy
      "\U000F059E", # windy-variant
      "\U000F14E4", # sunny-off
      ]

  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_80
    size: 80
    bpp: 4
    glyphs: [
      "\U000F0594", # clear-night
      "\U000F0590", # cloudy
      "\U000F0F2F", # exceptional
      "\U000F0591", # fog
      "\U000F0592", # hail
      "\U000F0593", # lightning
      "\U000F067E", # lightning-rainy
      "\U000F0595", # partlycloudy
      "\U000F0596", # pouring
      "\U000F0597", # rainy
      "\U000F0598", # snowy
      "\U000F067F", # snowy-rainy
      "\U000F0599", # sunny
      "\U000F059D", # windy
      "\U000F059E", # windy-variant
      "\U000F14E4", # sunny-off
      ]

  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_50
    size: 50
    bpp: 4
    glyphs: [
      "\U000F0594", # clear-night
      "\U000F0590", # cloudy
      "\U000F0F2F", # exceptional
      "\U000F0591", # fog
      "\U000F0592", # hail
      "\U000F0593", # lightning
      "\U000F067E", # lightning-rainy
      "\U000F0595", # partlycloudy
      "\U000F0596", # pouring
      "\U000F0597", # rainy
      "\U000F0598", # snowy
      "\U000F067F", # snowy-rainy
      "\U000F0599", # sunny
      "\U000F059D", # windy
      "\U000F059E", # windy-variant
      "\U000F14E4", # sunny-off
      ]

  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_40
    size: 40
    bpp: 4
    glyphs: [
      "\U000F0594", # clear-night
      "\U000F0590", # cloudy
      "\U000F0F2F", # exceptional
      "\U000F0591", # fog
      "\U000F0592", # hail
      "\U000F0593", # lightning
      "\U000F067E", # lightning-rainy
      "\U000F0595", # partlycloudy
      "\U000F0596", # pouring
      "\U000F0597", # rainy
      "\U000F0598", # snowy
      "\U000F067F", # snowy-rainy
      "\U000F0599", # sunny
      "\U000F059D", # windy
      "\U000F059E", # windy-variant
      "\U000F14E4", # sunny-off
      ]

  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_20
    size: 20
    bpp: 4
    glyphs: [
      "\U000F0594", # clear-night
      "\U000F0590", # cloudy
      "\U000F0F2F", # exceptional
      "\U000F0591", # fog
      "\U000F0592", # hail
      "\U000F0593", # lightning
      "\U000F067E", # lightning-rainy
      "\U000F0595", # partlycloudy
      "\U000F0596", # pouring
      "\U000F0597", # rainy
      "\U000F0598", # snowy
      "\U000F067F", # snowy-rainy
      "\U000F0599", # sunny
      "\U000F059D", # windy
      "\U000F059E", # windy-variant
      "\U000F14E4", # sunny-off
      ]

# ===================================================================
# WEATHER TEXT SENSORS (LVGL Widget Text Updaters)
# ===================================================================
# These text sensors allow updating LVGL label widgets from Home Assistant
# They are internal (not exposed to HA) and just bridge sensor data to UI

text:
  # Weather Forecast Page - Main weather display
  - platform: lvgl
    name: weather_today_tempap
    internal: true
    widget: lbl_weather_today_tempap
    mode: text
  - platform: lvgl
    name: weather_today_outdoor_temp
    internal: true
    widget: lbl_weather_today_outdoor_temp
    mode: text

  # Daily Forecast Page - Day 2
  - platform: lvgl
    name: forecast_day2_header
    internal: true
    widget: lbl_forecast_day2_header
    mode: text
  - platform: lvgl
    name: forecast_day2_icon
    internal: true
    widget: lbl_forecast_day2_icon
    mode: text
  - platform: lvgl
    name: forecast_day2_condition
    internal: true
    widget: lbl_forecast_day2_condition
    mode: text
  - platform: lvgl
    name: forecast_day2_temps
    internal: true
    widget: lbl_forecast_day2_temps
    mode: text
  - platform: lvgl
    name: forecast_day2_precip_prob
    internal: true
    widget: lbl_forecast_day2_precip_prob
    mode: text

  # Daily Forecast Page - Day 3
  - platform: lvgl
    name: forecast_day3_header
    internal: true
    widget: lbl_forecast_day3_header
    mode: text
  - platform: lvgl
    name: forecast_day3_icon
    internal: true
    widget: lbl_forecast_day3_icon
    mode: text
  - platform: lvgl
    name: forecast_day3_condition
    internal: true
    widget: lbl_forecast_day3_condition
    mode: text
  - platform: lvgl
    name: forecast_day3_temps
    internal: true
    widget: lbl_forecast_day3_temps
    mode: text
  - platform: lvgl
    name: forecast_day3_precip_prob
    internal: true
    widget: lbl_forecast_day3_precip_prob
    mode: text

  # Daily Forecast Page - Day 4
  - platform: lvgl
    name: forecast_day4_header
    internal: true
    widget: lbl_forecast_day4_header
    mode: text
  - platform: lvgl
    name: forecast_day4_icon
    internal: true
    widget: lbl_forecast_day4_icon
    mode: text
  - platform: lvgl
    name: forecast_day4_condition
    internal: true
    widget: lbl_forecast_day4_condition
    mode: text
  - platform: lvgl
    name: forecast_day4_temps
    internal: true
    widget: lbl_forecast_day4_temps
    mode: text
  - platform: lvgl
    name: forecast_day4_precip_prob
    internal: true
    widget: lbl_forecast_day4_precip_prob
    mode: text

  # Daily Forecast Page - Day 5
  - platform: lvgl
    name: forecast_day5_header
    internal: true
    widget: lbl_forecast_day5_header
    mode: text
  - platform: lvgl
    name: forecast_day5_icon
    internal: true
    widget: lbl_forecast_day5_icon
    mode: text
  - platform: lvgl
    name: forecast_day5_condition
    internal: true
    widget: lbl_forecast_day5_condition
    mode: text
  - platform: lvgl
    name: forecast_day5_temps
    internal: true
    widget: lbl_forecast_day5_temps
    mode: text
  - platform: lvgl
    name: forecast_day5_precip_prob
    internal: true
    widget: lbl_forecast_day5_precip_prob
    mode: text

  # Daily Forecast Page - Day 6
  - platform: lvgl
    name: forecast_day6_header
    internal: true
    widget: lbl_forecast_day6_header
    mode: text
  - platform: lvgl
    name: forecast_day6_icon
    internal: true
    widget: lbl_forecast_day6_icon
    mode: text
  - platform: lvgl
    name: forecast_day6_condition
    internal: true
    widget: lbl_forecast_day6_condition
    mode: text
  - platform: lvgl
    name: forecast_day6_temps
    internal: true
    widget: lbl_forecast_day6_temps
    mode: text
  - platform: lvgl
    name: forecast_day6_precip_prob
    internal: true
    widget: lbl_forecast_day6_precip_prob
    mode: text

  # Daily Forecast Page - Day 7
  - platform: lvgl
    name: forecast_day7_header
    internal: true
    widget: lbl_forecast_day7_header
    mode: text
  - platform: lvgl
    name: forecast_day7_icon
    internal: true
    widget: lbl_forecast_day7_icon
    mode: text
  - platform: lvgl
    name: forecast_day7_condition
    internal: true
    widget: lbl_forecast_day7_condition
    mode: text
  - platform: lvgl
    name: forecast_day7_temps
    internal: true
    widget: lbl_forecast_day7_temps
    mode: text
  - platform: lvgl
    name: forecast_day7_precip_prob
    internal: true
    widget: lbl_forecast_day7_precip_prob
    mode: text

  # Daily Forecast Page - Day 8
  - platform: lvgl
    name: forecast_day8_header
    internal: true
    widget: lbl_forecast_day8_header
    mode: text
  - platform: lvgl
    name: forecast_day8_icon
    internal: true
    widget: lbl_forecast_day8_icon
    mode: text
  - platform: lvgl
    name: forecast_day8_condition
    internal: true
    widget: lbl_forecast_day8_condition
    mode: text
  - platform: lvgl
    name: forecast_day8_temps
    internal: true
    widget: lbl_forecast_day8_temps
    mode: text
  - platform: lvgl
    name: forecast_day8_precip_prob
    internal: true
    widget: lbl_forecast_day8_precip_prob
    mode: text

  # Daily Forecast Page - Day 9
  - platform: lvgl
    name: forecast_day9_header
    internal: true
    widget: lbl_forecast_day9_header
    mode: text
  - platform: lvgl
    name: forecast_day9_icon
    internal: true
    widget: lbl_forecast_day9_icon
    mode: text
  - platform: lvgl
    name: forecast_day9_condition
    internal: true
    widget: lbl_forecast_day9_condition
    mode: text
  - platform: lvgl
    name: forecast_day9_temps
    internal: true
    widget: lbl_forecast_day9_temps
    mode: text
  - platform: lvgl
    name: forecast_day9_precip_prob
    internal: true
    widget: lbl_forecast_day9_precip_prob
    mode: text

  # Daily Forecast Page - Day 10
  - platform: lvgl
    name: forecast_day10_header
    internal: true
    widget: lbl_forecast_day10_header
    mode: text
  - platform: lvgl
    name: forecast_day10_icon
    internal: true
    widget: lbl_forecast_day10_icon
    mode: text
  - platform: lvgl
    name: forecast_day10_condition
    internal: true
    widget: lbl_forecast_day10_condition
    mode: text
  - platform: lvgl
    name: forecast_day10_temps
    internal: true
    widget: lbl_forecast_day10_temps
    mode: text
  - platform: lvgl
    name: forecast_day10_precip_prob
    internal: true
    widget: lbl_forecast_day10_precip_prob
    mode: text
