# Daily Forecast Page (Page 5)
# 10-day forecast overview
id: daily_forecast_page
  bg_color: 0x000000
  bg_opa: COVER
  scrollbar_mode: "OFF"
  on_load:
    - script.execute: page_transition_cleanup
    - lambda: 'id(current_page_index) = 5;'  # daily_forecast_page
  widgets:
    # Page Header
    - label:
        text: "9-Day Forecast"
        align: TOP_MID
        y: 5
        text_font: montserrat_18
        text_color: my_white
        text_align: CENTER

    # Day 2 Card
    - obj:
        width: 170
        height: SIZE_CONTENT
        align: TOP_MID
        y: 40
        bg_color: 0x101010
        bg_opa: COVER
        border_width: 0
        radius: 12
        pad_all: 12
        scrollbar_mode: "OFF"
        layout:
          type: flex
          flex_flow: column
          pad_row: 6
        widgets:
          - label:
              id: lbl_forecast_day2_header
              text: "Day +2 (--/--)"
              text_font: montserrat_18
              text_color: my_white
          - label:
              id: lbl_forecast_day2_icon
              text: "--"
              text_font: icons_80
              text_color: my_white
          - label:
              id: lbl_forecast_day2_condition
              text: "---"
              text_font: montserrat_18
              text_color: my_white
              long_mode: SCROLL_CIRCULAR
          - label:
              id: lbl_forecast_day2_temps
              text: "H:--째 L:--째"
              text_font: montserrat_18
              text_color: my_white
          - label:
              id: lbl_forecast_day2_precip_prob
              text: "Rain: --%"
              text_font: montserrat_16
              text_color: my_white

    # Day 3 Card
    - obj:
        width: 170
        height: SIZE_CONTENT
        align: TOP_MID
        y: 340
        bg_color: 0x101010
        bg_opa: COVER
        border_width: 0
        radius: 12
        pad_all: 12
        scrollbar_mode: "OFF"
        layout:
          type: flex
          flex_flow: column
          pad_row: 6
        widgets:
          - label:
              id: lbl_forecast_day3_header
              text: "Day +3 (--/--)"
              text_font: montserrat_18
              text_color: my_white
          - label:
              id: lbl_forecast_day3_icon
              text: "--"
              text_font: icons_80
              text_color: my_white
          - label:
              id: lbl_forecast_day3_condition
              text: "---"
              text_font: montserrat_18
              text_color: my_white
          - label:
              id: lbl_forecast_day3_temps
              text: "H:--째 L:--째"
              text_font: montserrat_18
              text_color: my_white
          - label:
              id: lbl_forecast_day3_precip_prob
              text: "Rain: --%"
              text_font: montserrat_16
              text_color: my_white

    # Navigation button to access extended forecast (Days 4-10)
    - label:
        text: "More >"
        align: BOTTOM_MID
        y: -5
        text_font: montserrat_18
        text_color: my_gray
        text_align: CENTER

    - obj:
        id: nav_button_extended_forecast
        align: BOTTOM_MID
        x: 0
        y: 0
        width: 100
        height: 60
        bg_opa: 0
        border_width: 0
        clickable: true
        on_press:
          - logger.log: "Extended forecast 'More' button PRESSED!"
          - lvgl.page.show:
              id: forecast_days_4_5_page
              animation: OUT_LEFT
              time: 300ms

    - obj:
        id: nav_button_forecast
        align: TOP_RIGHT
        x: 0
        y: 0
        width: 100
        height: 100
        bg_opa: 0
        border_width: 0
        clickable: true
        on_press:
          - logger.log: "3-Day Forecast page nav button PRESSED!"
          - lambda: |-
              ESP_LOGI("touch", "Navigation button touched");
              id(last_auto_rotation_time) = millis();
              ESP_LOGD("touch", "Auto-rotation timer reset");
          - lvgl.page.next:
              animation: OUT_LEFT
              time: 300ms


  # Extended Forecast Pages (Days 4-10)
