# ============================================================================
# WiFi Core Package - Page Rotation Controls and WiFi Signal Sensor
# ============================================================================
# This package contains WiFi page rotation controls and the WiFi signal sensor.
#
# Included Components:
#   - Page rotation globals (enabled/order)
#   - Page rotation switch (enable/disable WiFi page in rotation)
#   - Page rotation order number control
#   - WiFi signal strength sensor (RSSI)
#
# Dependencies:
#   - WiFi component configured in main config
#   - wifi-display.yaml or wireguard-display.yaml for display logic
#   - lvgl-wifi-wireguard-page.yaml or lvgl-wifi-page.yaml for page definition
# ============================================================================

globals:
  # Page rotation settings - which pages are included
  - id: page_rotation_wifi_enabled
    type: bool
    restore_value: yes
    initial_value: 'true'

  # Page rotation order (1-6, lower numbers show first)
  - id: page_rotation_wifi_order
    type: int
    restore_value: yes
    initial_value: '2'

switch:
  - platform: template
    name: "Page Rotation: WiFi Page"
    id: page_rotation_wifi_switch
    icon: mdi:wifi
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    entity_category: "config"
    on_turn_on:
      - lambda: 'id(page_rotation_wifi_enabled) = true;'
      - logger.log: "WiFi page enabled in rotation"
    on_turn_off:
      - lambda: 'id(page_rotation_wifi_enabled) = false;'
      - logger.log: "WiFi page disabled in rotation"

number:
  # Page rotation order numbers (1-6, lower numbers show first)
  - platform: template
    name: "Page Order: WiFi Page"
    id: page_order_wifi
    icon: mdi:numeric
    restore_value: true
    initial_value: 2
    min_value: 1
    max_value: 6
    entity_category: "config"
    optimistic: true
    step: 1
    mode: box
    on_value:
      - lambda: 'id(page_rotation_wifi_order) = (int)x;'
      - logger.log:
          format: "WiFi page order set to %d"
          args: ['(int)x']

sensor:
  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
