# WiFi Display Package
# WiFi status display support for LVGL-based displays (without WireGuard)
#
# Usage:
#   packages:
#     wifi_display: !include packages/wifi-display.yaml
#
# This package provides:
#   - Global variables for tracking WiFi display state
#   - Optimized rendering flags to reduce unnecessary UI updates
#   - Interval-based updates for WiFi status display (every 5 seconds)
#
# Required LVGL widget IDs in your display configuration:
#   - wifi_stat: WiFi status indicator on AirQ page
#   - ym_image: WiFi logo image
#   - wifi_signal_label: Signal strength text label
#   - wifi_signal_bar: Signal strength bar widget
#   - wifi_ssid_label: SSID text label
#   - wifi_ip_label: IP address text label
#
# Required global variables in your main config:
#   - boot_complete: bool to track if boot is complete
#   - current_page_index: int for current page (assumes AirQ_page is index 1, wifi_page is index 2)
#
# Required color IDs in your display configuration:
#   - my_green: Color for connected state
#   - my_red: Color for disconnected state
#
# Required sensors in your main config:
#   - wifi_signal_db: WiFi RSSI sensor

# LVGL configuration for WiFi display
lvgl:
  gradients:
    - id: wifi_signal_gradient
      direction: hor
      dither: none
      stops:
        - color: 0xFF0000  # Red - weak signal
          position: 0
        - color: 0xFF8000  # Orange
          position: 64
        - color: 0xFFFF00  # Yellow
          position: 128
        - color: 0x80FF00  # Yellow-green
          position: 192
        - color: 0x00FF00  # Green - strong signal
          position: 255

# Global variables for WiFi display state tracking
globals:
  - id: wifi_stat_connected_state
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: wifi_logo_visible
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: wifi_signal_last_text
    type: std::string
    restore_value: no
    initial_value: ""
  - id: wifi_signal_needs_render
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: wifi_signal_bar_last_value
    type: float
    restore_value: no
    initial_value: '-200.0'
  - id: wifi_signal_bar_needs_render
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: wifi_ssid_last_text
    type: std::string
    restore_value: no
    initial_value: ""
  - id: wifi_ssid_needs_render
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: wifi_ip_last_text
    type: std::string
    restore_value: no
    initial_value: ""
  - id: wifi_ip_needs_render
    type: bool
    restore_value: no
    initial_value: 'false'

# Interval for updating WiFi display elements
# This runs every 5 seconds to update WiFi status, signal, SSID, and IP information
# Only updates when boot is complete
interval:
  - interval: 5s
    then:
      - if:
          condition:
            lambda: 'return id(boot_complete);'
          then:
            - if:
                condition:
                  wifi.connected:
                then:
                  # Update WiFi status indicator on AirQ page
                  - if:
                      condition:
                        lambda: 'return !id(wifi_stat_connected_state) && id(current_page_index) == 1;'  # AirQ_page
                      then:
                        - lvgl.widget.update:
                            id: wifi_stat
                            text_color: my_green
                  - if:
                      condition:
                        lambda: 'return !id(wifi_stat_connected_state);'
                      then:
                        - lambda: 'id(wifi_stat_connected_state) = true;'
                  # Show WiFi logo on wifi_page
                  - if:
                      condition:
                        lambda: 'return !id(wifi_logo_visible) && id(current_page_index) == 2;'  # wifi_page
                      then:
                        - lvgl.widget.show:
                            id: ym_image
                  - if:
                      condition:
                        lambda: 'return !id(wifi_logo_visible);'
                      then:
                        - lambda: 'id(wifi_logo_visible) = true;'
                  # Update WiFi signal strength text
                  - lambda: |-
                      char buffer[32];
                      snprintf(buffer, sizeof(buffer), "Signal: %.0f dBm", id(wifi_signal_db).state);
                      std::string new_text(buffer);
                      if (new_text != id(wifi_signal_last_text)) {
                        id(wifi_signal_last_text) = new_text;
                        id(wifi_signal_needs_render) = true;
                      }
                  - if:
                      condition:
                        lambda: 'return id(wifi_signal_needs_render) && id(current_page_index) == 2;'  # wifi_page
                      then:
                        - lvgl.label.update:
                            id: wifi_signal_label
                            text: !lambda 'return id(wifi_signal_last_text);'
                        - lambda: 'id(wifi_signal_needs_render) = false;'
                  # Update WiFi signal bar
                  - lambda: |-
                      float signal = id(wifi_signal_db).state;
                      if (std::isnan(signal)) {
                        signal = -200.0f;
                      }
                      if (signal != id(wifi_signal_bar_last_value)) {
                        id(wifi_signal_bar_last_value) = signal;
                        id(wifi_signal_bar_needs_render) = true;
                      }
                  - if:
                      condition:
                        lambda: 'return id(wifi_signal_bar_needs_render) && id(current_page_index) == 2;'  # wifi_page
                      then:
                        - lvgl.bar.update:
                            id: wifi_signal_bar
                            value: !lambda 'return id(wifi_signal_bar_last_value);'
                        - lambda: 'id(wifi_signal_bar_needs_render) = false;'
                  # Update WiFi SSID
                  - lambda: |-
                      std::string ssid = esphome::wifi::global_wifi_component->wifi_ssid();
                      std::string new_text = std::string("SSID: ") + ssid;
                      if (new_text != id(wifi_ssid_last_text)) {
                        id(wifi_ssid_last_text) = new_text;
                        id(wifi_ssid_needs_render) = true;
                      }
                  - if:
                      condition:
                        lambda: 'return id(wifi_ssid_needs_render) && id(current_page_index) == 2;'  # wifi_page
                      then:
                        - lvgl.label.update:
                            id: wifi_ssid_label
                            text: !lambda 'return id(wifi_ssid_last_text);'
                        - lambda: 'id(wifi_ssid_needs_render) = false;'
                  # Update WiFi IP address
                  - lambda: |-
                      auto addresses = esphome::wifi::global_wifi_component->get_ip_addresses();
                      std::string ip_text = "IP: Not assigned";
                      if (!addresses.empty()) {
                        ip_text = std::string("IP: ") + addresses[0].str();
                      }
                      if (ip_text != id(wifi_ip_last_text)) {
                        id(wifi_ip_last_text) = ip_text;
                        id(wifi_ip_needs_render) = true;
                      }
                  - if:
                      condition:
                        lambda: 'return id(wifi_ip_needs_render) && id(current_page_index) == 2;'  # wifi_page
                      then:
                        - lvgl.label.update:
                            id: wifi_ip_label
                            text: !lambda 'return id(wifi_ip_last_text);'
                        - lambda: 'id(wifi_ip_needs_render) = false;'
                else:
                  # WiFi disconnected - show disconnected state
                  - if:
                      condition:
                        lambda: 'return id(wifi_stat_connected_state) && id(current_page_index) == 1;'  # AirQ_page
                      then:
                        - lvgl.widget.update:
                            id: wifi_stat
                            text_color: my_red
                  - lambda: 'id(wifi_stat_connected_state) = false;'
                  # Hide WiFi logo on AirQ page when disconnected
                  - if:
                      condition:
                        lambda: 'return id(wifi_logo_visible) && id(current_page_index) == 1;'  # AirQ_page
                      then:
                        - lvgl.widget.hide:
                            id: ym_image
                  - if:
                      condition:
                        lambda: 'return id(wifi_logo_visible);'
                      then:
                        - lambda: 'id(wifi_logo_visible) = false;'
                  # Update disconnected signal text
                  - lambda: |-
                      const std::string new_text = "Signal: --";
                      if (new_text != id(wifi_signal_last_text)) {
                        id(wifi_signal_last_text) = new_text;
                        id(wifi_signal_needs_render) = true;
                      }
                  - if:
                      condition:
                        lambda: 'return id(wifi_signal_needs_render) && id(current_page_index) == 2;'  # wifi_page
                      then:
                        - lvgl.label.update:
                            id: wifi_signal_label
                            text: !lambda 'return id(wifi_signal_last_text);'
                        - lambda: 'id(wifi_signal_needs_render) = false;'
                  # Update disconnected signal bar
                  - lambda: |-
                      float new_value = -200.0f;
                      if (new_value != id(wifi_signal_bar_last_value)) {
                        id(wifi_signal_bar_last_value) = new_value;
                        id(wifi_signal_bar_needs_render) = true;
                      }
                  - if:
                      condition:
                        lambda: 'return id(wifi_signal_bar_needs_render) && id(current_page_index) == 2;'  # wifi_page
                      then:
                        - lvgl.bar.update:
                            id: wifi_signal_bar
                            value: !lambda 'return id(wifi_signal_bar_last_value);'
                        - lambda: 'id(wifi_signal_bar_needs_render) = false;'
                  # Update disconnected SSID
                  - lambda: |-
                      const std::string ssid_text = "SSID: Not connected";
                      if (ssid_text != id(wifi_ssid_last_text)) {
                        id(wifi_ssid_last_text) = ssid_text;
                        id(wifi_ssid_needs_render) = true;
                      }
                  - if:
                      condition:
                        lambda: 'return id(wifi_ssid_needs_render) && id(current_page_index) == 2;'  # wifi_page
                      then:
                        - lvgl.label.update:
                            id: wifi_ssid_label
                            text: !lambda 'return id(wifi_ssid_last_text);'
                        - lambda: 'id(wifi_ssid_needs_render) = false;'
                  # Update disconnected IP
                  - lambda: |-
                      const std::string ip_text = "IP: Not connected";
                      if (ip_text != id(wifi_ip_last_text)) {
                        id(wifi_ip_last_text) = ip_text;
                        id(wifi_ip_needs_render) = true;
                      }
                  - if:
                      condition:
                        lambda: 'return id(wifi_ip_needs_render) && id(current_page_index) == 2;'  # wifi_page
                      then:
                        - lvgl.label.update:
                            id: wifi_ip_label
                            text: !lambda 'return id(wifi_ip_last_text);'
                        - lambda: 'id(wifi_ip_needs_render) = false;'
