# ============================================================================
# WiFi Stubs Package - Stub Globals for WiFi-Disabled Mode
# ============================================================================
# This package provides stub globals for when WiFi page is disabled.
# It prevents compilation errors in page rotation logic by defining the
# required globals with disabled/neutral values.
#
# Usage:
#   1. Comment out wifi-core.yaml in main config
#   2. Include this package instead: wifi_stubs: !include packages/wifi-stubs.yaml
#   3. Comment out wifi-display.yaml and lvgl-wifi-*-page.yaml includes
#   4. The firmware will compile without WiFi page features
#
# Note: Similar pattern to airq-stubs.yaml and weather-stubs.yaml
# ============================================================================

globals:
  # Page rotation settings - which pages are included
  - id: page_rotation_wifi_enabled
    type: bool
    restore_value: no
    initial_value: 'false'

  - id: page_rotation_wifi_order
    type: int
    restore_value: no
    initial_value: '99'
