# ============================================================================
# WireGuard Stubs - Placeholder for Disabled WireGuard
# ============================================================================
# This file provides stub definitions for WireGuard-related components when
# WireGuard is disabled via feature flags.
#
# Purpose:
#   - Prevents "ID not found" errors in core files that reference WireGuard
#   - Defines all WireGuard globals as disabled/false
#   - Zero memory footprint
#
# Usage:
#   Automatically loaded when feature_wireguard = "false"
# ============================================================================

# Note: WireGuard typically doesn't have many globals that need stubbing
# since it's mostly self-contained. This file exists for consistency
# and future-proofing.

# If your core files reference any WireGuard-specific IDs, add stubs here.
# Example:
# globals:
#   - id: wireguard_enabled
#     type: bool
#     restore_value: no
#     initial_value: 'false'
