# active_packages.yaml

# Active Packages Configuration for halo-v1 Project

packages:
  - name: wifi
    version: latest
    enabled: true

  - name: ble
    version: latest
    enabled: true

  - name: weather
    version: latest
    enabled: true

  - name: wireguard
    version: latest
    enabled: true

  - name: lvgl
    version: latest
    enabled: true

# Additional configurations can be added as needed.