# ============================================================================
# Meta Wrapper for Halo-v1-Core.yaml
# ============================================================================
# This wrapper prevents ESPHome's double-parsing issue when a file loaded
# via packages: contains its own packages: block.
#
# ESPHome's loader can mistakenly interpret the parent key (device_core:) as
# a component name when package nesting occurs. This meta file isolates the
# packages: block to prevent that issue.
#
# USAGE:
#   Instead of loading Halo-v1-Core.yaml directly, load this meta file:
#
#   packages:
#     device_core:
#       url: https://github.com/truffshuff/halo.git
#       ref: main
#       files:
#         - TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/meta/Halo-v1-Core-Meta.yaml
#       refresh: always
#
# This is Option 2 from the ESPHome nested packages workaround.
# ============================================================================

packages:
  core_base: !include ../Halo-v1-Core.yaml
